"use client";

// Auto-generated: ALL 1512 Phosphor Icons registry
// Token naming: ic-{kebab-name} (e.g., ic-acorn, ic-address-book)
// This file is generated — do not edit manually

import type { ComponentType } from "react";

import {
  Acorn,
  AddressBook,
  AddressBookTabs,
  AirTrafficControl,
  Airplane,
  AirplaneInFlight,
  AirplaneLanding,
  AirplaneTakeoff,
  AirplaneTaxiing,
  AirplaneTilt,
  Airplay,
  Alarm,
  Alien,
  AlignBottom,
  AlignBottomSimple,
  AlignCenterHorizontal,
  AlignCenterHorizontalSimple,
  AlignCenterVertical,
  AlignCenterVerticalSimple,
  AlignLeft,
  AlignLeftSimple,
  AlignRight,
  AlignRightSimple,
  AlignTop,
  AlignTopSimple,
  AmazonLogo,
  Ambulance,
  Anchor,
  AnchorSimple,
  AndroidLogo,
  Angle,
  AngularLogo,
  Aperture,
  AppStoreLogo,
  AppWindow,
  AppleLogo,
  ApplePodcastsLogo,
  ApproximateEquals,
  Archive,
  Armchair,
  ArrowArcLeft,
  ArrowArcRight,
  ArrowBendDoubleUpLeft,
  ArrowBendDoubleUpRight,
  ArrowBendDownLeft,
  ArrowBendDownRight,
  ArrowBendLeftDown,
  ArrowBendLeftUp,
  ArrowBendRightDown,
  ArrowBendRightUp,
  ArrowBendUpLeft,
  ArrowBendUpRight,
  ArrowCircleDown,
  ArrowCircleDownLeft,
  ArrowCircleDownRight,
  ArrowCircleLeft,
  ArrowCircleRight,
  ArrowCircleUp,
  ArrowCircleUpLeft,
  ArrowCircleUpRight,
  ArrowClockwise,
  ArrowCounterClockwise,
  ArrowDown,
  ArrowDownLeft,
  ArrowDownRight,
  ArrowElbowDownLeft,
  ArrowElbowDownRight,
  ArrowElbowLeft,
  ArrowElbowLeftDown,
  ArrowElbowLeftUp,
  ArrowElbowRight,
  ArrowElbowRightDown,
  ArrowElbowRightUp,
  ArrowElbowUpLeft,
  ArrowElbowUpRight,
  ArrowFatDown,
  ArrowFatLeft,
  ArrowFatLineDown,
  ArrowFatLineLeft,
  ArrowFatLineRight,
  ArrowFatLineUp,
  ArrowFatLinesDown,
  ArrowFatLinesLeft,
  ArrowFatLinesRight,
  ArrowFatLinesUp,
  ArrowFatRight,
  ArrowFatUp,
  ArrowLeft,
  ArrowLineDown,
  ArrowLineDownLeft,
  ArrowLineDownRight,
  ArrowLineLeft,
  ArrowLineRight,
  ArrowLineUp,
  ArrowLineUpLeft,
  ArrowLineUpRight,
  ArrowRight,
  ArrowSquareDown,
  ArrowSquareDownLeft,
  ArrowSquareDownRight,
  ArrowSquareIn,
  ArrowSquareLeft,
  ArrowSquareOut,
  ArrowSquareRight,
  ArrowSquareUp,
  ArrowSquareUpLeft,
  ArrowSquareUpRight,
  ArrowUDownLeft,
  ArrowUDownRight,
  ArrowULeftDown,
  ArrowULeftUp,
  ArrowURightDown,
  ArrowURightUp,
  ArrowUUpLeft,
  ArrowUUpRight,
  ArrowUp,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowsClockwise,
  ArrowsCounterClockwise,
  ArrowsDownUp,
  ArrowsHorizontal,
  ArrowsIn,
  ArrowsInCardinal,
  ArrowsInLineHorizontal,
  ArrowsInLineVertical,
  ArrowsInSimple,
  ArrowsLeftRight,
  ArrowsMerge,
  ArrowsOut,
  ArrowsOutCardinal,
  ArrowsOutLineHorizontal,
  ArrowsOutLineVertical,
  ArrowsOutSimple,
  ArrowsSplit,
  ArrowsVertical,
  Article,
  ArticleMedium,
  ArticleNyTimes,
  Asclepius,
  Asterisk,
  AsteriskSimple,
  At,
  Atom,
  Avocado,
  Axe,
  Baby,
  BabyCarriage,
  Backpack,
  Backspace,
  Bag,
  BagSimple,
  Balloon,
  Bandaids,
  Bank,
  Barbell,
  Barcode,
  Barn,
  Barricade,
  Baseball,
  BaseballCap,
  BaseballHelmet,
  Basket,
  Basketball,
  Bathtub,
  BatteryCharging,
  BatteryChargingVertical,
  BatteryEmpty,
  BatteryFull,
  BatteryHigh,
  BatteryLow,
  BatteryMedium,
  BatteryPlus,
  BatteryPlusVertical,
  BatteryVerticalEmpty,
  BatteryVerticalFull,
  BatteryVerticalHigh,
  BatteryVerticalLow,
  BatteryVerticalMedium,
  BatteryWarning,
  BatteryWarningVertical,
  BeachBall,
  Beanie,
  Bed,
  BeerBottle,
  BeerStein,
  BehanceLogo,
  Bell,
  BellRinging,
  BellSimple,
  BellSimpleRinging,
  BellSimpleSlash,
  BellSimpleZ,
  BellSlash,
  BellZ,
  Belt,
  BezierCurve,
  Bicycle,
  Binary,
  Binoculars,
  Biohazard,
  Bird,
  Blueprint,
  Bluetooth,
  BluetoothConnected,
  BluetoothSlash,
  BluetoothX,
  Boat,
  Bomb,
  Bone,
  Book,
  BookBookmark,
  BookOpen,
  BookOpenText,
  BookOpenUser,
  Bookmark,
  BookmarkSimple,
  Bookmarks,
  BookmarksSimple,
  Books,
  Boot,
  Boules,
  BoundingBox,
  BowlFood,
  BowlSteam,
  BowlingBall,
  BoxArrowDown,
  BoxArrowUp,
  BoxingGlove,
  BracketsAngle,
  BracketsCurly,
  BracketsRound,
  BracketsSquare,
  Brain,
  Brandy,
  Bread,
  Bridge,
  Briefcase,
  BriefcaseMetal,
  Broadcast,
  Broom,
  Browser,
  Browsers,
  Bug,
  BugBeetle,
  BugDroid,
  Building,
  BuildingApartment,
  BuildingOffice,
  Buildings,
  Bulldozer,
  Bus,
  Butterfly,
  CableCar,
  Cactus,
  Cake,
  Calculator,
  Calendar,
  CalendarBlank,
  CalendarCheck,
  CalendarDot,
  CalendarDots,
  CalendarHeart,
  CalendarMinus,
  CalendarPlus,
  CalendarSlash,
  CalendarStar,
  CalendarX,
  CallBell,
  Camera,
  CameraPlus,
  CameraRotate,
  CameraSlash,
  Campfire,
  Car,
  CarBattery,
  CarProfile,
  CarSimple,
  Cardholder,
  Cards,
  CardsThree,
  CaretCircleDoubleDown,
  CaretCircleDoubleLeft,
  CaretCircleDoubleRight,
  CaretCircleDoubleUp,
  CaretCircleDown,
  CaretCircleLeft,
  CaretCircleRight,
  CaretCircleUp,
  CaretCircleUpDown,
  CaretDoubleDown,
  CaretDoubleLeft,
  CaretDoubleRight,
  CaretDoubleUp,
  CaretDown,
  CaretLeft,
  CaretLineDown,
  CaretLineLeft,
  CaretLineRight,
  CaretLineUp,
  CaretRight,
  CaretUp,
  CaretUpDown,
  Carrot,
  CashRegister,
  CassetteTape,
  CastleTurret,
  Cat,
  CellSignalFull,
  CellSignalHigh,
  CellSignalLow,
  CellSignalMedium,
  CellSignalNone,
  CellSignalSlash,
  CellSignalX,
  CellTower,
  Certificate,
  Chair,
  Chalkboard,
  ChalkboardSimple,
  ChalkboardTeacher,
  Champagne,
  ChargingStation,
  ChartBar,
  ChartBarHorizontal,
  ChartDonut,
  ChartLine,
  ChartLineDown,
  ChartLineUp,
  ChartPie,
  ChartPieSlice,
  ChartPolar,
  ChartScatter,
  Chat,
  ChatCentered,
  ChatCenteredDots,
  ChatCenteredSlash,
  ChatCenteredText,
  ChatCircle,
  ChatCircleDots,
  ChatCircleSlash,
  ChatCircleText,
  ChatDots,
  ChatSlash,
  ChatTeardrop,
  ChatTeardropDots,
  ChatTeardropSlash,
  ChatTeardropText,
  ChatText,
  Chats,
  ChatsCircle,
  ChatsTeardrop,
  Check,
  CheckCircle,
  CheckFat,
  CheckSquare,
  CheckSquareOffset,
  Checkerboard,
  Checks,
  Cheers,
  Cheese,
  ChefHat,
  Cherries,
  Church,
  Cigarette,
  CigaretteSlash,
  Circle,
  CircleDashed,
  CircleHalf,
  CircleHalfTilt,
  CircleNotch,
  CirclesFour,
  CirclesThree,
  CirclesThreePlus,
  Circuitry,
  City,
  Clipboard,
  ClipboardText,
  Clock,
  ClockAfternoon,
  ClockClockwise,
  ClockCountdown,
  ClockCounterClockwise,
  ClockUser,
  ClosedCaptioning,
  Cloud,
  CloudArrowDown,
  CloudArrowUp,
  CloudCheck,
  CloudFog,
  CloudLightning,
  CloudMoon,
  CloudRain,
  CloudSlash,
  CloudSnow,
  CloudSun,
  CloudWarning,
  CloudX,
  Clover,
  Club,
  CoatHanger,
  CodaLogo,
  Code,
  CodeBlock,
  CodeSimple,
  CodepenLogo,
  CodesandboxLogo,
  Coffee,
  CoffeeBean,
  Coin,
  CoinVertical,
  Coins,
  Columns,
  ColumnsPlusLeft,
  ColumnsPlusRight,
  Command,
  Compass,
  CompassRose,
  CompassTool,
  ComputerTower,
  Confetti,
  ContactlessPayment,
  Control,
  Cookie,
  CookingPot,
  Copy,
  CopySimple,
  Copyleft,
  Copyright,
  CornersIn,
  CornersOut,
  Couch,
  CourtBasketball,
  Cow,
  CowboyHat,
  Cpu,
  Crane,
  CraneTower,
  CreditCard,
  Cricket,
  Crop,
  Cross,
  Crosshair,
  CrosshairSimple,
  Crown,
  CrownCross,
  CrownSimple,
  Cube,
  CubeFocus,
  CubeTransparent,
  CurrencyBtc,
  CurrencyCircleDollar,
  CurrencyCny,
  CurrencyDollar,
  CurrencyDollarSimple,
  CurrencyEth,
  CurrencyEur,
  CurrencyGbp,
  CurrencyInr,
  CurrencyJpy,
  CurrencyKrw,
  CurrencyKzt,
  CurrencyNgn,
  CurrencyRub,
  Cursor,
  CursorClick,
  CursorText,
  Cylinder,
  Database,
  Desk,
  Desktop,
  DesktopTower,
  Detective,
  DevToLogo,
  DeviceMobile,
  DeviceMobileCamera,
  DeviceMobileSlash,
  DeviceMobileSpeaker,
  DeviceRotate,
  DeviceTablet,
  DeviceTabletCamera,
  DeviceTabletSpeaker,
  Devices,
  Diamond,
  DiamondsFour,
  DiceFive,
  DiceFour,
  DiceOne,
  DiceSix,
  DiceThree,
  DiceTwo,
  Disc,
  DiscoBall,
  DiscordLogo,
  Divide,
  Dna,
  Dog,
  Door,
  DoorOpen,
  Dot,
  DotOutline,
  DotsNine,
  DotsSix,
  DotsSixVertical,
  DotsThree,
  DotsThreeCircle,
  DotsThreeCircleVertical,
  DotsThreeOutline,
  DotsThreeOutlineVertical,
  DotsThreeVertical,
  Download,
  DownloadSimple,
  Dress,
  Dresser,
  DribbbleLogo,
  Drone,
  Drop,
  DropHalf,
  DropHalfBottom,
  DropSimple,
  DropSlash,
  DropboxLogo,
  Ear,
  EarSlash,
  Egg,
  EggCrack,
  Eject,
  EjectSimple,
  Elevator,
  Empty,
  Engine,
  Envelope,
  EnvelopeOpen,
  EnvelopeSimple,
  EnvelopeSimpleOpen,
  Equalizer,
  Equals,
  Eraser,
  EscalatorDown,
  EscalatorUp,
  Exam,
  ExclamationMark,
  Exclude,
  ExcludeSquare,
  Export,
  Eye,
  EyeClosed,
  EyeSlash,
  Eyedropper,
  EyedropperSample,
  Eyeglasses,
  Eyes,
  FaceMask,
  FacebookLogo,
  Factory,
  Faders,
  FadersHorizontal,
  FalloutShelter,
  Fan,
  Farm,
  FastForward,
  FastForwardCircle,
  Feather,
  FediverseLogo,
  FigmaLogo,
  File,
  FileArchive,
  FileArrowDown,
  FileArrowUp,
  FileAudio,
  FileC,
  FileCSharp,
  FileCloud,
  FileCode,
  FileCpp,
  FileCss,
  FileCsv,
  FileDashed,
  FileDoc,
  FileHtml,
  FileImage,
  FileIni,
  FileJpg,
  FileJs,
  FileJsx,
  FileLock,
  FileMagnifyingGlass,
  FileMd,
  FileMinus,
  FilePdf,
  FilePlus,
  FilePng,
  FilePpt,
  FilePy,
  FileRs,
  FileSql,
  FileSvg,
  FileText,
  FileTs,
  FileTsx,
  FileTxt,
  FileVideo,
  FileVue,
  FileX,
  FileXls,
  FileZip,
  Files,
  FilmReel,
  FilmScript,
  FilmSlate,
  FilmStrip,
  Fingerprint,
  FingerprintSimple,
  FinnTheHuman,
  Fire,
  FireExtinguisher,
  FireSimple,
  FireTruck,
  FirstAid,
  FirstAidKit,
  Fish,
  FishSimple,
  Flag,
  FlagBanner,
  FlagBannerFold,
  FlagCheckered,
  FlagPennant,
  Flame,
  Flashlight,
  Flask,
  FlipHorizontal,
  FlipVertical,
  FloppyDisk,
  FloppyDiskBack,
  FlowArrow,
  Flower,
  FlowerLotus,
  FlowerTulip,
  FlyingSaucer,
  Folder,
  FolderDashed,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderPlus,
  FolderSimple,
  FolderSimpleDashed,
  FolderSimpleLock,
  FolderSimpleMinus,
  FolderSimplePlus,
  FolderSimpleStar,
  FolderSimpleUser,
  FolderStar,
  FolderUser,
  Folders,
  Football,
  FootballHelmet,
  Footprints,
  ForkKnife,
  FourK,
  FrameCorners,
  FramerLogo,
  Function,
  Funnel,
  FunnelSimple,
  FunnelSimpleX,
  FunnelX,
  GameController,
  Garage,
  GasCan,
  GasPump,
  Gauge,
  Gavel,
  Gear,
  GearFine,
  GearSix,
  GenderFemale,
  GenderIntersex,
  GenderMale,
  GenderNeuter,
  GenderNonbinary,
  GenderTransgender,
  Ghost,
  Gif,
  Gift,
  GitBranch,
  GitCommit,
  GitDiff,
  GitFork,
  GitMerge,
  GitPullRequest,
  GithubLogo,
  GitlabLogo,
  GitlabLogoSimple,
  Globe,
  GlobeHemisphereEast,
  GlobeHemisphereWest,
  GlobeSimple,
  GlobeSimpleX,
  GlobeStand,
  GlobeX,
  Goggles,
  Golf,
  GoodreadsLogo,
  GoogleCardboardLogo,
  GoogleChromeLogo,
  GoogleDriveLogo,
  GoogleLogo,
  GooglePhotosLogo,
  GooglePlayLogo,
  GooglePodcastsLogo,
  Gps,
  GpsFix,
  GpsSlash,
  Gradient,
  GraduationCap,
  Grains,
  GrainsSlash,
  Graph,
  GraphicsCard,
  GreaterThan,
  GreaterThanOrEqual,
  GridFour,
  GridNine,
  Guitar,
  HairDryer,
  Hamburger,
  Hammer,
  Hand,
  HandArrowDown,
  HandArrowUp,
  HandCoins,
  HandDeposit,
  HandEye,
  HandFist,
  HandGrabbing,
  HandHeart,
  HandPalm,
  HandPeace,
  HandPointing,
  HandSoap,
  HandSwipeLeft,
  HandSwipeRight,
  HandTap,
  HandWaving,
  HandWithdraw,
  Handbag,
  HandbagSimple,
  HandsClapping,
  HandsPraying,
  Handshake,
  HardDrive,
  HardDrives,
  HardHat,
  Hash,
  HashStraight,
  HeadCircuit,
  Headlights,
  Headphones,
  Headset,
  Heart,
  HeartBreak,
  HeartHalf,
  HeartStraight,
  HeartStraightBreak,
  Heartbeat,
  Hexagon,
  HighDefinition,
  HighHeel,
  Highlighter,
  HighlighterCircle,
  Hockey,
  Hoodie,
  Horse,
  Hospital,
  Hourglass,
  HourglassHigh,
  HourglassLow,
  HourglassMedium,
  HourglassSimple,
  HourglassSimpleHigh,
  HourglassSimpleLow,
  HourglassSimpleMedium,
  House,
  HouseLine,
  HouseSimple,
  Hurricane,
  IceCream,
  IdentificationBadge,
  IdentificationCard,
  Image,
  ImageBroken,
  ImageSquare,
  Images,
  ImagesSquare,
  Infinity,
  Info,
  InstagramLogo,
  Intersect,
  IntersectSquare,
  IntersectThree,
  Intersection,
  Invoice,
  Island,
  Jar,
  JarLabel,
  Jeep,
  Joystick,
  Kanban,
  Key,
  KeyReturn,
  Keyboard,
  Keyhole,
  Knife,
  Ladder,
  LadderSimple,
  Lamp,
  LampPendant,
  Laptop,
  Lasso,
  LastfmLogo,
  Layout,
  Leaf,
  Lectern,
  Lego,
  LegoSmiley,
  LessThan,
  LessThanOrEqual,
  LetterCircleH,
  LetterCircleP,
  LetterCircleV,
  Lifebuoy,
  Lightbulb,
  LightbulbFilament,
  Lighthouse,
  Lightning,
  LightningA,
  LightningSlash,
  LineSegment,
  LineSegments,
  LineVertical,
  Link,
  LinkBreak,
  LinkSimple,
  LinkSimpleBreak,
  LinkSimpleHorizontal,
  LinkSimpleHorizontalBreak,
  LinkedinLogo,
  LinktreeLogo,
  LinuxLogo,
  List,
  ListBullets,
  ListChecks,
  ListDashes,
  ListHeart,
  ListMagnifyingGlass,
  ListNumbers,
  ListPlus,
  ListStar,
  Lock,
  LockKey,
  LockKeyOpen,
  LockLaminated,
  LockLaminatedOpen,
  LockOpen,
  LockSimple,
  LockSimpleOpen,
  Lockers,
  Log,
  MagicWand,
  Magnet,
  MagnetStraight,
  MagnifyingGlass,
  MagnifyingGlassMinus,
  MagnifyingGlassPlus,
  Mailbox,
  MapPin,
  MapPinArea,
  MapPinLine,
  MapPinPlus,
  MapPinSimple,
  MapPinSimpleArea,
  MapPinSimpleLine,
  MapTrifold,
  MarkdownLogo,
  MarkerCircle,
  Martini,
  MaskHappy,
  MaskSad,
  MastodonLogo,
  MathOperations,
  MatrixLogo,
  Medal,
  MedalMilitary,
  MediumLogo,
  Megaphone,
  MegaphoneSimple,
  MemberOf,
  Memory,
  MessengerLogo,
  MetaLogo,
  Meteor,
  Metronome,
  Microphone,
  MicrophoneSlash,
  MicrophoneStage,
  Microscope,
  MicrosoftExcelLogo,
  MicrosoftOutlookLogo,
  MicrosoftPowerpointLogo,
  MicrosoftTeamsLogo,
  MicrosoftWordLogo,
  Minus,
  MinusCircle,
  MinusSquare,
  Money,
  MoneyWavy,
  Monitor,
  MonitorArrowUp,
  MonitorPlay,
  Moon,
  MoonStars,
  Moped,
  MopedFront,
  Mosque,
  Motorcycle,
  Mountains,
  Mouse,
  MouseLeftClick,
  MouseMiddleClick,
  MouseRightClick,
  MouseScroll,
  MouseSimple,
  MusicNote,
  MusicNoteSimple,
  MusicNotes,
  MusicNotesMinus,
  MusicNotesPlus,
  MusicNotesSimple,
  NavigationArrow,
  Needle,
  Network,
  NetworkSlash,
  NetworkX,
  Newspaper,
  NewspaperClipping,
  NotEquals,
  NotMemberOf,
  NotSubsetOf,
  NotSupersetOf,
  Notches,
  Note,
  NoteBlank,
  NotePencil,
  Notebook,
  Notepad,
  Notification,
  NotionLogo,
  NuclearPlant,
  NumberCircleEight,
  NumberCircleFive,
  NumberCircleFour,
  NumberCircleNine,
  NumberCircleOne,
  NumberCircleSeven,
  NumberCircleSix,
  NumberCircleThree,
  NumberCircleTwo,
  NumberCircleZero,
  NumberEight,
  NumberFive,
  NumberFour,
  NumberNine,
  NumberOne,
  NumberSeven,
  NumberSix,
  NumberSquareEight,
  NumberSquareFive,
  NumberSquareFour,
  NumberSquareNine,
  NumberSquareOne,
  NumberSquareSeven,
  NumberSquareSix,
  NumberSquareThree,
  NumberSquareTwo,
  NumberSquareZero,
  NumberThree,
  NumberTwo,
  NumberZero,
  Numpad,
  Nut,
  NyTimesLogo,
  Octagon,
  OfficeChair,
  Onigiri,
  OpenAiLogo,
  Option,
  Orange,
  OrangeSlice,
  Oven,
  Package,
  PaintBrush,
  PaintBrushBroad,
  PaintBrushHousehold,
  PaintBucket,
  PaintRoller,
  Palette,
  Panorama,
  Pants,
  PaperPlane,
  PaperPlaneRight,
  PaperPlaneTilt,
  Paperclip,
  PaperclipHorizontal,
  Parachute,
  Paragraph,
  Parallelogram,
  Park,
  Password,
  Path,
  PatreonLogo,
  Pause,
  PauseCircle,
  PawPrint,
  PaypalLogo,
  Peace,
  Pen,
  PenNib,
  PenNibStraight,
  Pencil,
  PencilCircle,
  PencilLine,
  PencilRuler,
  PencilSimple,
  PencilSimpleLine,
  PencilSimpleSlash,
  PencilSlash,
  Pentagon,
  Pentagram,
  Pepper,
  Percent,
  Person,
  PersonArmsSpread,
  PersonSimple,
  PersonSimpleBike,
  PersonSimpleCircle,
  PersonSimpleHike,
  PersonSimpleRun,
  PersonSimpleSki,
  PersonSimpleSnowboard,
  PersonSimpleSwim,
  PersonSimpleTaiChi,
  PersonSimpleThrow,
  PersonSimpleWalk,
  Perspective,
  Phone,
  PhoneCall,
  PhoneDisconnect,
  PhoneIncoming,
  PhoneList,
  PhoneOutgoing,
  PhonePause,
  PhonePlus,
  PhoneSlash,
  PhoneTransfer,
  PhoneX,
  PhosphorLogo,
  Pi,
  PianoKeys,
  PicnicTable,
  PictureInPicture,
  PiggyBank,
  Pill,
  PingPong,
  PintGlass,
  PinterestLogo,
  Pinwheel,
  Pipe,
  PipeWrench,
  PixLogo,
  Pizza,
  Placeholder,
  Planet,
  Plant,
  Play,
  PlayCircle,
  PlayPause,
  Playlist,
  Plug,
  PlugCharging,
  Plugs,
  PlugsConnected,
  Plus,
  PlusCircle,
  PlusMinus,
  PlusSquare,
  PokerChip,
  PoliceCar,
  Polygon,
  Popcorn,
  Popsicle,
  PottedPlant,
  Power,
  Prescription,
  Presentation,
  PresentationChart,
  Printer,
  Prohibit,
  ProhibitInset,
  ProjectorScreen,
  ProjectorScreenChart,
  Pulse,
  PushPin,
  PushPinSimple,
  PushPinSimpleSlash,
  PushPinSlash,
  PuzzlePiece,
  QrCode,
  Question,
  QuestionMark,
  Queue,
  Quotes,
  Rabbit,
  Racquet,
  Radical,
  Radio,
  RadioButton,
  Radioactive,
  Rainbow,
  RainbowCloud,
  Ranking,
  ReadCvLogo,
  Receipt,
  ReceiptX,
  Record,
  Rectangle,
  RectangleDashed,
  Recycle,
  RedditLogo,
  Repeat,
  RepeatOnce,
  ReplitLogo,
  Resize,
  Rewind,
  RewindCircle,
  RoadHorizon,
  Robot,
  Rocket,
  RocketLaunch,
  Rows,
  RowsPlusBottom,
  RowsPlusTop,
  Rss,
  RssSimple,
  Rug,
  Ruler,
  Sailboat,
  Scales,
  Scan,
  ScanSmiley,
  Scissors,
  Scooter,
  Screencast,
  Screwdriver,
  Scribble,
  ScribbleLoop,
  Scroll,
  Seal,
  SealCheck,
  SealPercent,
  SealQuestion,
  SealWarning,
  Seat,
  Seatbelt,
  SecurityCamera,
  Selection,
  SelectionAll,
  SelectionBackground,
  SelectionForeground,
  SelectionInverse,
  SelectionPlus,
  SelectionSlash,
  Shapes,
  Share,
  ShareFat,
  ShareNetwork,
  Shield,
  ShieldCheck,
  ShieldCheckered,
  ShieldChevron,
  ShieldPlus,
  ShieldSlash,
  ShieldStar,
  ShieldWarning,
  ShippingContainer,
  ShirtFolded,
  ShootingStar,
  ShoppingBag,
  ShoppingBagOpen,
  ShoppingCart,
  ShoppingCartSimple,
  Shovel,
  Shower,
  Shrimp,
  Shuffle,
  ShuffleAngular,
  ShuffleSimple,
  Sidebar,
  SidebarSimple,
  Sigma,
  SignIn,
  SignOut,
  Signature,
  Signpost,
  SimCard,
  Siren,
  SketchLogo,
  SkipBack,
  SkipBackCircle,
  SkipForward,
  SkipForwardCircle,
  Skull,
  SkypeLogo,
  SlackLogo,
  Sliders,
  SlidersHorizontal,
  Slideshow,
  Smiley,
  SmileyAngry,
  SmileyBlank,
  SmileyMeh,
  SmileyMelting,
  SmileyNervous,
  SmileySad,
  SmileySticker,
  SmileyWink,
  SmileyXEyes,
  SnapchatLogo,
  Sneaker,
  SneakerMove,
  Snowflake,
  SoccerBall,
  Sock,
  SolarPanel,
  SolarRoof,
  SortAscending,
  SortDescending,
  SoundcloudLogo,
  Spade,
  Sparkle,
  SpeakerHifi,
  SpeakerHigh,
  SpeakerLow,
  SpeakerNone,
  SpeakerSimpleHigh,
  SpeakerSimpleLow,
  SpeakerSimpleNone,
  SpeakerSimpleSlash,
  SpeakerSimpleX,
  SpeakerSlash,
  SpeakerX,
  Speedometer,
  Sphere,
  Spinner,
  SpinnerBall,
  SpinnerGap,
  Spiral,
  SplitHorizontal,
  SplitVertical,
  SpotifyLogo,
  SprayBottle,
  Square,
  SquareHalf,
  SquareHalfBottom,
  SquareLogo,
  SquareSplitHorizontal,
  SquareSplitVertical,
  SquaresFour,
  Stack,
  StackMinus,
  StackOverflowLogo,
  StackPlus,
  StackSimple,
  Stairs,
  Stamp,
  StandardDefinition,
  Star,
  StarAndCrescent,
  StarFour,
  StarHalf,
  StarOfDavid,
  SteamLogo,
  SteeringWheel,
  Steps,
  Stethoscope,
  Sticker,
  Stool,
  Stop,
  StopCircle,
  Storefront,
  Strategy,
  StripeLogo,
  Student,
  SubsetOf,
  SubsetProperOf,
  Subtitles,
  SubtitlesSlash,
  Subtract,
  SubtractSquare,
  Subway,
  Suitcase,
  SuitcaseRolling,
  SuitcaseSimple,
  Sun,
  SunDim,
  SunHorizon,
  Sunglasses,
  SupersetOf,
  SupersetProperOf,
  Swap,
  Swatches,
  SwimmingPool,
  Sword,
  Synagogue,
  Syringe,
  TShirt,
  Table,
  Tabs,
  Tag,
  TagChevron,
  TagSimple,
  Target,
  Taxi,
  TeaBag,
  TelegramLogo,
  Television,
  TelevisionSimple,
  TennisBall,
  Tent,
  Terminal,
  TerminalWindow,
  TestTube,
  TextAUnderline,
  TextAa,
  TextAlignCenter,
  TextAlignJustify,
  TextAlignLeft,
  TextAlignRight,
  TextB,
  TextColumns,
  TextH,
  TextHFive,
  TextHFour,
  TextHOne,
  TextHSix,
  TextHThree,
  TextHTwo,
  TextIndent,
  TextItalic,
  TextOutdent,
  TextStrikethrough,
  TextSubscript,
  TextSuperscript,
  TextT,
  TextTSlash,
  TextUnderline,
  Textbox,
  Thermometer,
  ThermometerCold,
  ThermometerHot,
  ThermometerSimple,
  ThreadsLogo,
  ThreeD,
  ThumbsDown,
  ThumbsUp,
  Ticket,
  TidalLogo,
  TiktokLogo,
  Tilde,
  Timer,
  TipJar,
  Tipi,
  Tire,
  ToggleLeft,
  ToggleRight,
  Toilet,
  ToiletPaper,
  Toolbox,
  Tooth,
  Tornado,
  Tote,
  ToteSimple,
  Towel,
  Tractor,
  Trademark,
  TrademarkRegistered,
  TrafficCone,
  TrafficSign,
  TrafficSignal,
  Train,
  TrainRegional,
  TrainSimple,
  Tram,
  Translate,
  Trash,
  TrashSimple,
  Tray,
  TrayArrowDown,
  TrayArrowUp,
  TreasureChest,
  Tree,
  TreeEvergreen,
  TreePalm,
  TreeStructure,
  TreeView,
  TrendDown,
  TrendUp,
  Triangle,
  TriangleDashed,
  Trolley,
  TrolleySuitcase,
  Trophy,
  Truck,
  TruckTrailer,
  TumblrLogo,
  TwitchLogo,
  TwitterLogo,
  Umbrella,
  UmbrellaSimple,
  Union,
  Unite,
  UniteSquare,
  Upload,
  UploadSimple,
  Usb,
  User,
  UserCheck,
  UserCircle,
  UserCircleCheck,
  UserCircleDashed,
  UserCircleGear,
  UserCircleMinus,
  UserCirclePlus,
  UserFocus,
  UserGear,
  UserList,
  UserMinus,
  UserPlus,
  UserRectangle,
  UserSound,
  UserSquare,
  UserSwitch,
  Users,
  UsersFour,
  UsersThree,
  Van,
  Vault,
  VectorThree,
  VectorTwo,
  Vibrate,
  Video,
  VideoCamera,
  VideoCameraSlash,
  VideoConference,
  Vignette,
  VinylRecord,
  VirtualReality,
  Virus,
  Visor,
  Voicemail,
  Volleyball,
  Wall,
  Wallet,
  Warehouse,
  Warning,
  WarningCircle,
  WarningDiamond,
  WarningOctagon,
  WashingMachine,
  Watch,
  WaveSawtooth,
  WaveSine,
  WaveSquare,
  WaveTriangle,
  Waveform,
  WaveformSlash,
  Waves,
  Webcam,
  WebcamSlash,
  WebhooksLogo,
  WechatLogo,
  WhatsappLogo,
  Wheelchair,
  WheelchairMotion,
  WifiHigh,
  WifiLow,
  WifiMedium,
  WifiNone,
  WifiSlash,
  WifiX,
  Wind,
  Windmill,
  WindowsLogo,
  Wine,
  Wrench,
  X,
  XCircle,
  XLogo,
  XSquare,
  Yarn,
  YinYang,
  YoutubeLogo
} from "@phosphor-icons/react";

type IconComponent = ComponentType<{ size?: number; weight?: "thin" | "light" | "regular" | "bold" | "fill" | "duotone"; className?: string }>;

export const ICON_REGISTRY: Record<string, IconComponent> = {
  "ic-acorn": Acorn,
  "ic-address-book": AddressBook,
  "ic-address-book-tabs": AddressBookTabs,
  "ic-air-traffic-control": AirTrafficControl,
  "ic-airplane": Airplane,
  "ic-airplane-in-flight": AirplaneInFlight,
  "ic-airplane-landing": AirplaneLanding,
  "ic-airplane-takeoff": AirplaneTakeoff,
  "ic-airplane-taxiing": AirplaneTaxiing,
  "ic-airplane-tilt": AirplaneTilt,
  "ic-airplay": Airplay,
  "ic-alarm": Alarm,
  "ic-alien": Alien,
  "ic-align-bottom": AlignBottom,
  "ic-align-bottom-simple": AlignBottomSimple,
  "ic-align-center-horizontal": AlignCenterHorizontal,
  "ic-align-center-horizontal-simple": AlignCenterHorizontalSimple,
  "ic-align-center-vertical": AlignCenterVertical,
  "ic-align-center-vertical-simple": AlignCenterVerticalSimple,
  "ic-align-left": AlignLeft,
  "ic-align-left-simple": AlignLeftSimple,
  "ic-align-right": AlignRight,
  "ic-align-right-simple": AlignRightSimple,
  "ic-align-top": AlignTop,
  "ic-align-top-simple": AlignTopSimple,
  "ic-amazon-logo": AmazonLogo,
  "ic-ambulance": Ambulance,
  "ic-anchor": Anchor,
  "ic-anchor-simple": AnchorSimple,
  "ic-android-logo": AndroidLogo,
  "ic-angle": Angle,
  "ic-angular-logo": AngularLogo,
  "ic-aperture": Aperture,
  "ic-app-store-logo": AppStoreLogo,
  "ic-app-window": AppWindow,
  "ic-apple-logo": AppleLogo,
  "ic-apple-podcasts-logo": ApplePodcastsLogo,
  "ic-approximate-equals": ApproximateEquals,
  "ic-archive": Archive,
  "ic-armchair": Armchair,
  "ic-arrow-arc-left": ArrowArcLeft,
  "ic-arrow-arc-right": ArrowArcRight,
  "ic-arrow-bend-double-up-left": ArrowBendDoubleUpLeft,
  "ic-arrow-bend-double-up-right": ArrowBendDoubleUpRight,
  "ic-arrow-bend-down-left": ArrowBendDownLeft,
  "ic-arrow-bend-down-right": ArrowBendDownRight,
  "ic-arrow-bend-left-down": ArrowBendLeftDown,
  "ic-arrow-bend-left-up": ArrowBendLeftUp,
  "ic-arrow-bend-right-down": ArrowBendRightDown,
  "ic-arrow-bend-right-up": ArrowBendRightUp,
  "ic-arrow-bend-up-left": ArrowBendUpLeft,
  "ic-arrow-bend-up-right": ArrowBendUpRight,
  "ic-arrow-circle-down": ArrowCircleDown,
  "ic-arrow-circle-down-left": ArrowCircleDownLeft,
  "ic-arrow-circle-down-right": ArrowCircleDownRight,
  "ic-arrow-circle-left": ArrowCircleLeft,
  "ic-arrow-circle-right": ArrowCircleRight,
  "ic-arrow-circle-up": ArrowCircleUp,
  "ic-arrow-circle-up-left": ArrowCircleUpLeft,
  "ic-arrow-circle-up-right": ArrowCircleUpRight,
  "ic-arrow-clockwise": ArrowClockwise,
  "ic-arrow-counter-clockwise": ArrowCounterClockwise,
  "ic-arrow-down": ArrowDown,
  "ic-arrow-down-left": ArrowDownLeft,
  "ic-arrow-down-right": ArrowDownRight,
  "ic-arrow-elbow-down-left": ArrowElbowDownLeft,
  "ic-arrow-elbow-down-right": ArrowElbowDownRight,
  "ic-arrow-elbow-left": ArrowElbowLeft,
  "ic-arrow-elbow-left-down": ArrowElbowLeftDown,
  "ic-arrow-elbow-left-up": ArrowElbowLeftUp,
  "ic-arrow-elbow-right": ArrowElbowRight,
  "ic-arrow-elbow-right-down": ArrowElbowRightDown,
  "ic-arrow-elbow-right-up": ArrowElbowRightUp,
  "ic-arrow-elbow-up-left": ArrowElbowUpLeft,
  "ic-arrow-elbow-up-right": ArrowElbowUpRight,
  "ic-arrow-fat-down": ArrowFatDown,
  "ic-arrow-fat-left": ArrowFatLeft,
  "ic-arrow-fat-line-down": ArrowFatLineDown,
  "ic-arrow-fat-line-left": ArrowFatLineLeft,
  "ic-arrow-fat-line-right": ArrowFatLineRight,
  "ic-arrow-fat-line-up": ArrowFatLineUp,
  "ic-arrow-fat-lines-down": ArrowFatLinesDown,
  "ic-arrow-fat-lines-left": ArrowFatLinesLeft,
  "ic-arrow-fat-lines-right": ArrowFatLinesRight,
  "ic-arrow-fat-lines-up": ArrowFatLinesUp,
  "ic-arrow-fat-right": ArrowFatRight,
  "ic-arrow-fat-up": ArrowFatUp,
  "ic-arrow-left": ArrowLeft,
  "ic-arrow-line-down": ArrowLineDown,
  "ic-arrow-line-down-left": ArrowLineDownLeft,
  "ic-arrow-line-down-right": ArrowLineDownRight,
  "ic-arrow-line-left": ArrowLineLeft,
  "ic-arrow-line-right": ArrowLineRight,
  "ic-arrow-line-up": ArrowLineUp,
  "ic-arrow-line-up-left": ArrowLineUpLeft,
  "ic-arrow-line-up-right": ArrowLineUpRight,
  "ic-arrow-right": ArrowRight,
  "ic-arrow-square-down": ArrowSquareDown,
  "ic-arrow-square-down-left": ArrowSquareDownLeft,
  "ic-arrow-square-down-right": ArrowSquareDownRight,
  "ic-arrow-square-in": ArrowSquareIn,
  "ic-arrow-square-left": ArrowSquareLeft,
  "ic-arrow-square-out": ArrowSquareOut,
  "ic-arrow-square-right": ArrowSquareRight,
  "ic-arrow-square-up": ArrowSquareUp,
  "ic-arrow-square-up-left": ArrowSquareUpLeft,
  "ic-arrow-square-up-right": ArrowSquareUpRight,
  "ic-arrow-u-down-left": ArrowUDownLeft,
  "ic-arrow-u-down-right": ArrowUDownRight,
  "ic-arrow-u-left-down": ArrowULeftDown,
  "ic-arrow-u-left-up": ArrowULeftUp,
  "ic-arrow-u-right-down": ArrowURightDown,
  "ic-arrow-u-right-up": ArrowURightUp,
  "ic-arrow-u-up-left": ArrowUUpLeft,
  "ic-arrow-u-up-right": ArrowUUpRight,
  "ic-arrow-up": ArrowUp,
  "ic-arrow-up-left": ArrowUpLeft,
  "ic-arrow-up-right": ArrowUpRight,
  "ic-arrows-clockwise": ArrowsClockwise,
  "ic-arrows-counter-clockwise": ArrowsCounterClockwise,
  "ic-arrows-down-up": ArrowsDownUp,
  "ic-arrows-horizontal": ArrowsHorizontal,
  "ic-arrows-in": ArrowsIn,
  "ic-arrows-in-cardinal": ArrowsInCardinal,
  "ic-arrows-in-line-horizontal": ArrowsInLineHorizontal,
  "ic-arrows-in-line-vertical": ArrowsInLineVertical,
  "ic-arrows-in-simple": ArrowsInSimple,
  "ic-arrows-left-right": ArrowsLeftRight,
  "ic-arrows-merge": ArrowsMerge,
  "ic-arrows-out": ArrowsOut,
  "ic-arrows-out-cardinal": ArrowsOutCardinal,
  "ic-arrows-out-line-horizontal": ArrowsOutLineHorizontal,
  "ic-arrows-out-line-vertical": ArrowsOutLineVertical,
  "ic-arrows-out-simple": ArrowsOutSimple,
  "ic-arrows-split": ArrowsSplit,
  "ic-arrows-vertical": ArrowsVertical,
  "ic-article": Article,
  "ic-article-medium": ArticleMedium,
  "ic-article-ny-times": ArticleNyTimes,
  "ic-asclepius": Asclepius,
  "ic-asterisk": Asterisk,
  "ic-asterisk-simple": AsteriskSimple,
  "ic-at": At,
  "ic-atom": Atom,
  "ic-avocado": Avocado,
  "ic-axe": Axe,
  "ic-baby": Baby,
  "ic-baby-carriage": BabyCarriage,
  "ic-backpack": Backpack,
  "ic-backspace": Backspace,
  "ic-bag": Bag,
  "ic-bag-simple": BagSimple,
  "ic-balloon": Balloon,
  "ic-bandaids": Bandaids,
  "ic-bank": Bank,
  "ic-barbell": Barbell,
  "ic-barcode": Barcode,
  "ic-barn": Barn,
  "ic-barricade": Barricade,
  "ic-baseball": Baseball,
  "ic-baseball-cap": BaseballCap,
  "ic-baseball-helmet": BaseballHelmet,
  "ic-basket": Basket,
  "ic-basketball": Basketball,
  "ic-bathtub": Bathtub,
  "ic-battery-charging": BatteryCharging,
  "ic-battery-charging-vertical": BatteryChargingVertical,
  "ic-battery-empty": BatteryEmpty,
  "ic-battery-full": BatteryFull,
  "ic-battery-high": BatteryHigh,
  "ic-battery-low": BatteryLow,
  "ic-battery-medium": BatteryMedium,
  "ic-battery-plus": BatteryPlus,
  "ic-battery-plus-vertical": BatteryPlusVertical,
  "ic-battery-vertical-empty": BatteryVerticalEmpty,
  "ic-battery-vertical-full": BatteryVerticalFull,
  "ic-battery-vertical-high": BatteryVerticalHigh,
  "ic-battery-vertical-low": BatteryVerticalLow,
  "ic-battery-vertical-medium": BatteryVerticalMedium,
  "ic-battery-warning": BatteryWarning,
  "ic-battery-warning-vertical": BatteryWarningVertical,
  "ic-beach-ball": BeachBall,
  "ic-beanie": Beanie,
  "ic-bed": Bed,
  "ic-beer-bottle": BeerBottle,
  "ic-beer-stein": BeerStein,
  "ic-behance-logo": BehanceLogo,
  "ic-bell": Bell,
  "ic-bell-ringing": BellRinging,
  "ic-bell-simple": BellSimple,
  "ic-bell-simple-ringing": BellSimpleRinging,
  "ic-bell-simple-slash": BellSimpleSlash,
  "ic-bell-simple-z": BellSimpleZ,
  "ic-bell-slash": BellSlash,
  "ic-bell-z": BellZ,
  "ic-belt": Belt,
  "ic-bezier-curve": BezierCurve,
  "ic-bicycle": Bicycle,
  "ic-binary": Binary,
  "ic-binoculars": Binoculars,
  "ic-biohazard": Biohazard,
  "ic-bird": Bird,
  "ic-blueprint": Blueprint,
  "ic-bluetooth": Bluetooth,
  "ic-bluetooth-connected": BluetoothConnected,
  "ic-bluetooth-slash": BluetoothSlash,
  "ic-bluetooth-x": BluetoothX,
  "ic-boat": Boat,
  "ic-bomb": Bomb,
  "ic-bone": Bone,
  "ic-book": Book,
  "ic-book-bookmark": BookBookmark,
  "ic-book-open": BookOpen,
  "ic-book-open-text": BookOpenText,
  "ic-book-open-user": BookOpenUser,
  "ic-bookmark": Bookmark,
  "ic-bookmark-simple": BookmarkSimple,
  "ic-bookmarks": Bookmarks,
  "ic-bookmarks-simple": BookmarksSimple,
  "ic-books": Books,
  "ic-boot": Boot,
  "ic-boules": Boules,
  "ic-bounding-box": BoundingBox,
  "ic-bowl-food": BowlFood,
  "ic-bowl-steam": BowlSteam,
  "ic-bowling-ball": BowlingBall,
  "ic-box-arrow-down": BoxArrowDown,
  "ic-box-arrow-up": BoxArrowUp,
  "ic-boxing-glove": BoxingGlove,
  "ic-brackets-angle": BracketsAngle,
  "ic-brackets-curly": BracketsCurly,
  "ic-brackets-round": BracketsRound,
  "ic-brackets-square": BracketsSquare,
  "ic-brain": Brain,
  "ic-brandy": Brandy,
  "ic-bread": Bread,
  "ic-bridge": Bridge,
  "ic-briefcase": Briefcase,
  "ic-briefcase-metal": BriefcaseMetal,
  "ic-broadcast": Broadcast,
  "ic-broom": Broom,
  "ic-browser": Browser,
  "ic-browsers": Browsers,
  "ic-bug": Bug,
  "ic-bug-beetle": BugBeetle,
  "ic-bug-droid": BugDroid,
  "ic-building": Building,
  "ic-building-apartment": BuildingApartment,
  "ic-building-office": BuildingOffice,
  "ic-buildings": Buildings,
  "ic-bulldozer": Bulldozer,
  "ic-bus": Bus,
  "ic-butterfly": Butterfly,
  "ic-cable-car": CableCar,
  "ic-cactus": Cactus,
  "ic-cake": Cake,
  "ic-calculator": Calculator,
  "ic-calendar": Calendar,
  "ic-calendar-blank": CalendarBlank,
  "ic-calendar-check": CalendarCheck,
  "ic-calendar-dot": CalendarDot,
  "ic-calendar-dots": CalendarDots,
  "ic-calendar-heart": CalendarHeart,
  "ic-calendar-minus": CalendarMinus,
  "ic-calendar-plus": CalendarPlus,
  "ic-calendar-slash": CalendarSlash,
  "ic-calendar-star": CalendarStar,
  "ic-calendar-x": CalendarX,
  "ic-call-bell": CallBell,
  "ic-camera": Camera,
  "ic-camera-plus": CameraPlus,
  "ic-camera-rotate": CameraRotate,
  "ic-camera-slash": CameraSlash,
  "ic-campfire": Campfire,
  "ic-car": Car,
  "ic-car-battery": CarBattery,
  "ic-car-profile": CarProfile,
  "ic-car-simple": CarSimple,
  "ic-cardholder": Cardholder,
  "ic-cards": Cards,
  "ic-cards-three": CardsThree,
  "ic-caret-circle-double-down": CaretCircleDoubleDown,
  "ic-caret-circle-double-left": CaretCircleDoubleLeft,
  "ic-caret-circle-double-right": CaretCircleDoubleRight,
  "ic-caret-circle-double-up": CaretCircleDoubleUp,
  "ic-caret-circle-down": CaretCircleDown,
  "ic-caret-circle-left": CaretCircleLeft,
  "ic-caret-circle-right": CaretCircleRight,
  "ic-caret-circle-up": CaretCircleUp,
  "ic-caret-circle-up-down": CaretCircleUpDown,
  "ic-caret-double-down": CaretDoubleDown,
  "ic-caret-double-left": CaretDoubleLeft,
  "ic-caret-double-right": CaretDoubleRight,
  "ic-caret-double-up": CaretDoubleUp,
  "ic-caret-down": CaretDown,
  "ic-caret-left": CaretLeft,
  "ic-caret-line-down": CaretLineDown,
  "ic-caret-line-left": CaretLineLeft,
  "ic-caret-line-right": CaretLineRight,
  "ic-caret-line-up": CaretLineUp,
  "ic-caret-right": CaretRight,
  "ic-caret-up": CaretUp,
  "ic-caret-up-down": CaretUpDown,
  "ic-carrot": Carrot,
  "ic-cash-register": CashRegister,
  "ic-cassette-tape": CassetteTape,
  "ic-castle-turret": CastleTurret,
  "ic-cat": Cat,
  "ic-cell-signal-full": CellSignalFull,
  "ic-cell-signal-high": CellSignalHigh,
  "ic-cell-signal-low": CellSignalLow,
  "ic-cell-signal-medium": CellSignalMedium,
  "ic-cell-signal-none": CellSignalNone,
  "ic-cell-signal-slash": CellSignalSlash,
  "ic-cell-signal-x": CellSignalX,
  "ic-cell-tower": CellTower,
  "ic-certificate": Certificate,
  "ic-chair": Chair,
  "ic-chalkboard": Chalkboard,
  "ic-chalkboard-simple": ChalkboardSimple,
  "ic-chalkboard-teacher": ChalkboardTeacher,
  "ic-champagne": Champagne,
  "ic-charging-station": ChargingStation,
  "ic-chart-bar": ChartBar,
  "ic-chart-bar-horizontal": ChartBarHorizontal,
  "ic-chart-donut": ChartDonut,
  "ic-chart-line": ChartLine,
  "ic-chart-line-down": ChartLineDown,
  "ic-chart-line-up": ChartLineUp,
  "ic-chart-pie": ChartPie,
  "ic-chart-pie-slice": ChartPieSlice,
  "ic-chart-polar": ChartPolar,
  "ic-chart-scatter": ChartScatter,
  "ic-chat": Chat,
  "ic-chat-centered": ChatCentered,
  "ic-chat-centered-dots": ChatCenteredDots,
  "ic-chat-centered-slash": ChatCenteredSlash,
  "ic-chat-centered-text": ChatCenteredText,
  "ic-chat-circle": ChatCircle,
  "ic-chat-circle-dots": ChatCircleDots,
  "ic-chat-circle-slash": ChatCircleSlash,
  "ic-chat-circle-text": ChatCircleText,
  "ic-chat-dots": ChatDots,
  "ic-chat-slash": ChatSlash,
  "ic-chat-teardrop": ChatTeardrop,
  "ic-chat-teardrop-dots": ChatTeardropDots,
  "ic-chat-teardrop-slash": ChatTeardropSlash,
  "ic-chat-teardrop-text": ChatTeardropText,
  "ic-chat-text": ChatText,
  "ic-chats": Chats,
  "ic-chats-circle": ChatsCircle,
  "ic-chats-teardrop": ChatsTeardrop,
  "ic-check": Check,
  "ic-check-circle": CheckCircle,
  "ic-check-fat": CheckFat,
  "ic-check-square": CheckSquare,
  "ic-check-square-offset": CheckSquareOffset,
  "ic-checkerboard": Checkerboard,
  "ic-checks": Checks,
  "ic-cheers": Cheers,
  "ic-cheese": Cheese,
  "ic-chef-hat": ChefHat,
  "ic-cherries": Cherries,
  "ic-church": Church,
  "ic-cigarette": Cigarette,
  "ic-cigarette-slash": CigaretteSlash,
  "ic-circle": Circle,
  "ic-circle-dashed": CircleDashed,
  "ic-circle-half": CircleHalf,
  "ic-circle-half-tilt": CircleHalfTilt,
  "ic-circle-notch": CircleNotch,
  "ic-circles-four": CirclesFour,
  "ic-circles-three": CirclesThree,
  "ic-circles-three-plus": CirclesThreePlus,
  "ic-circuitry": Circuitry,
  "ic-city": City,
  "ic-clipboard": Clipboard,
  "ic-clipboard-text": ClipboardText,
  "ic-clock": Clock,
  "ic-clock-afternoon": ClockAfternoon,
  "ic-clock-clockwise": ClockClockwise,
  "ic-clock-countdown": ClockCountdown,
  "ic-clock-counter-clockwise": ClockCounterClockwise,
  "ic-clock-user": ClockUser,
  "ic-closed-captioning": ClosedCaptioning,
  "ic-cloud": Cloud,
  "ic-cloud-arrow-down": CloudArrowDown,
  "ic-cloud-arrow-up": CloudArrowUp,
  "ic-cloud-check": CloudCheck,
  "ic-cloud-fog": CloudFog,
  "ic-cloud-lightning": CloudLightning,
  "ic-cloud-moon": CloudMoon,
  "ic-cloud-rain": CloudRain,
  "ic-cloud-slash": CloudSlash,
  "ic-cloud-snow": CloudSnow,
  "ic-cloud-sun": CloudSun,
  "ic-cloud-warning": CloudWarning,
  "ic-cloud-x": CloudX,
  "ic-clover": Clover,
  "ic-club": Club,
  "ic-coat-hanger": CoatHanger,
  "ic-coda-logo": CodaLogo,
  "ic-code": Code,
  "ic-code-block": CodeBlock,
  "ic-code-simple": CodeSimple,
  "ic-codepen-logo": CodepenLogo,
  "ic-codesandbox-logo": CodesandboxLogo,
  "ic-coffee": Coffee,
  "ic-coffee-bean": CoffeeBean,
  "ic-coin": Coin,
  "ic-coin-vertical": CoinVertical,
  "ic-coins": Coins,
  "ic-columns": Columns,
  "ic-columns-plus-left": ColumnsPlusLeft,
  "ic-columns-plus-right": ColumnsPlusRight,
  "ic-command": Command,
  "ic-compass": Compass,
  "ic-compass-rose": CompassRose,
  "ic-compass-tool": CompassTool,
  "ic-computer-tower": ComputerTower,
  "ic-confetti": Confetti,
  "ic-contactless-payment": ContactlessPayment,
  "ic-control": Control,
  "ic-cookie": Cookie,
  "ic-cooking-pot": CookingPot,
  "ic-copy": Copy,
  "ic-copy-simple": CopySimple,
  "ic-copyleft": Copyleft,
  "ic-copyright": Copyright,
  "ic-corners-in": CornersIn,
  "ic-corners-out": CornersOut,
  "ic-couch": Couch,
  "ic-court-basketball": CourtBasketball,
  "ic-cow": Cow,
  "ic-cowboy-hat": CowboyHat,
  "ic-cpu": Cpu,
  "ic-crane": Crane,
  "ic-crane-tower": CraneTower,
  "ic-credit-card": CreditCard,
  "ic-cricket": Cricket,
  "ic-crop": Crop,
  "ic-cross": Cross,
  "ic-crosshair": Crosshair,
  "ic-crosshair-simple": CrosshairSimple,
  "ic-crown": Crown,
  "ic-crown-cross": CrownCross,
  "ic-crown-simple": CrownSimple,
  "ic-cube": Cube,
  "ic-cube-focus": CubeFocus,
  "ic-cube-transparent": CubeTransparent,
  "ic-currency-btc": CurrencyBtc,
  "ic-currency-circle-dollar": CurrencyCircleDollar,
  "ic-currency-cny": CurrencyCny,
  "ic-currency-dollar": CurrencyDollar,
  "ic-currency-dollar-simple": CurrencyDollarSimple,
  "ic-currency-eth": CurrencyEth,
  "ic-currency-eur": CurrencyEur,
  "ic-currency-gbp": CurrencyGbp,
  "ic-currency-inr": CurrencyInr,
  "ic-currency-jpy": CurrencyJpy,
  "ic-currency-krw": CurrencyKrw,
  "ic-currency-kzt": CurrencyKzt,
  "ic-currency-ngn": CurrencyNgn,
  "ic-currency-rub": CurrencyRub,
  "ic-cursor": Cursor,
  "ic-cursor-click": CursorClick,
  "ic-cursor-text": CursorText,
  "ic-cylinder": Cylinder,
  "ic-database": Database,
  "ic-desk": Desk,
  "ic-desktop": Desktop,
  "ic-desktop-tower": DesktopTower,
  "ic-detective": Detective,
  "ic-dev-to-logo": DevToLogo,
  "ic-device-mobile": DeviceMobile,
  "ic-device-mobile-camera": DeviceMobileCamera,
  "ic-device-mobile-slash": DeviceMobileSlash,
  "ic-device-mobile-speaker": DeviceMobileSpeaker,
  "ic-device-rotate": DeviceRotate,
  "ic-device-tablet": DeviceTablet,
  "ic-device-tablet-camera": DeviceTabletCamera,
  "ic-device-tablet-speaker": DeviceTabletSpeaker,
  "ic-devices": Devices,
  "ic-diamond": Diamond,
  "ic-diamonds-four": DiamondsFour,
  "ic-dice-five": DiceFive,
  "ic-dice-four": DiceFour,
  "ic-dice-one": DiceOne,
  "ic-dice-six": DiceSix,
  "ic-dice-three": DiceThree,
  "ic-dice-two": DiceTwo,
  "ic-disc": Disc,
  "ic-disco-ball": DiscoBall,
  "ic-discord-logo": DiscordLogo,
  "ic-divide": Divide,
  "ic-dna": Dna,
  "ic-dog": Dog,
  "ic-door": Door,
  "ic-door-open": DoorOpen,
  "ic-dot": Dot,
  "ic-dot-outline": DotOutline,
  "ic-dots-nine": DotsNine,
  "ic-dots-six": DotsSix,
  "ic-dots-six-vertical": DotsSixVertical,
  "ic-dots-three": DotsThree,
  "ic-dots-three-circle": DotsThreeCircle,
  "ic-dots-three-circle-vertical": DotsThreeCircleVertical,
  "ic-dots-three-outline": DotsThreeOutline,
  "ic-dots-three-outline-vertical": DotsThreeOutlineVertical,
  "ic-dots-three-vertical": DotsThreeVertical,
  "ic-download": Download,
  "ic-download-simple": DownloadSimple,
  "ic-dress": Dress,
  "ic-dresser": Dresser,
  "ic-dribbble-logo": DribbbleLogo,
  "ic-drone": Drone,
  "ic-drop": Drop,
  "ic-drop-half": DropHalf,
  "ic-drop-half-bottom": DropHalfBottom,
  "ic-drop-simple": DropSimple,
  "ic-drop-slash": DropSlash,
  "ic-dropbox-logo": DropboxLogo,
  "ic-ear": Ear,
  "ic-ear-slash": EarSlash,
  "ic-egg": Egg,
  "ic-egg-crack": EggCrack,
  "ic-eject": Eject,
  "ic-eject-simple": EjectSimple,
  "ic-elevator": Elevator,
  "ic-empty": Empty,
  "ic-engine": Engine,
  "ic-envelope": Envelope,
  "ic-envelope-open": EnvelopeOpen,
  "ic-envelope-simple": EnvelopeSimple,
  "ic-envelope-simple-open": EnvelopeSimpleOpen,
  "ic-equalizer": Equalizer,
  "ic-equals": Equals,
  "ic-eraser": Eraser,
  "ic-escalator-down": EscalatorDown,
  "ic-escalator-up": EscalatorUp,
  "ic-exam": Exam,
  "ic-exclamation-mark": ExclamationMark,
  "ic-exclude": Exclude,
  "ic-exclude-square": ExcludeSquare,
  "ic-export": Export,
  "ic-eye": Eye,
  "ic-eye-closed": EyeClosed,
  "ic-eye-slash": EyeSlash,
  "ic-eyedropper": Eyedropper,
  "ic-eyedropper-sample": EyedropperSample,
  "ic-eyeglasses": Eyeglasses,
  "ic-eyes": Eyes,
  "ic-face-mask": FaceMask,
  "ic-facebook-logo": FacebookLogo,
  "ic-factory": Factory,
  "ic-faders": Faders,
  "ic-faders-horizontal": FadersHorizontal,
  "ic-fallout-shelter": FalloutShelter,
  "ic-fan": Fan,
  "ic-farm": Farm,
  "ic-fast-forward": FastForward,
  "ic-fast-forward-circle": FastForwardCircle,
  "ic-feather": Feather,
  "ic-fediverse-logo": FediverseLogo,
  "ic-figma-logo": FigmaLogo,
  "ic-file": File,
  "ic-file-archive": FileArchive,
  "ic-file-arrow-down": FileArrowDown,
  "ic-file-arrow-up": FileArrowUp,
  "ic-file-audio": FileAudio,
  "ic-file-c": FileC,
  "ic-file-c-sharp": FileCSharp,
  "ic-file-cloud": FileCloud,
  "ic-file-code": FileCode,
  "ic-file-cpp": FileCpp,
  "ic-file-css": FileCss,
  "ic-file-csv": FileCsv,
  "ic-file-dashed": FileDashed,
  "ic-file-doc": FileDoc,
  "ic-file-html": FileHtml,
  "ic-file-image": FileImage,
  "ic-file-ini": FileIni,
  "ic-file-jpg": FileJpg,
  "ic-file-js": FileJs,
  "ic-file-jsx": FileJsx,
  "ic-file-lock": FileLock,
  "ic-file-magnifying-glass": FileMagnifyingGlass,
  "ic-file-md": FileMd,
  "ic-file-minus": FileMinus,
  "ic-file-pdf": FilePdf,
  "ic-file-plus": FilePlus,
  "ic-file-png": FilePng,
  "ic-file-ppt": FilePpt,
  "ic-file-py": FilePy,
  "ic-file-rs": FileRs,
  "ic-file-sql": FileSql,
  "ic-file-svg": FileSvg,
  "ic-file-text": FileText,
  "ic-file-ts": FileTs,
  "ic-file-tsx": FileTsx,
  "ic-file-txt": FileTxt,
  "ic-file-video": FileVideo,
  "ic-file-vue": FileVue,
  "ic-file-x": FileX,
  "ic-file-xls": FileXls,
  "ic-file-zip": FileZip,
  "ic-files": Files,
  "ic-film-reel": FilmReel,
  "ic-film-script": FilmScript,
  "ic-film-slate": FilmSlate,
  "ic-film-strip": FilmStrip,
  "ic-fingerprint": Fingerprint,
  "ic-fingerprint-simple": FingerprintSimple,
  "ic-finn-the-human": FinnTheHuman,
  "ic-fire": Fire,
  "ic-fire-extinguisher": FireExtinguisher,
  "ic-fire-simple": FireSimple,
  "ic-fire-truck": FireTruck,
  "ic-first-aid": FirstAid,
  "ic-first-aid-kit": FirstAidKit,
  "ic-fish": Fish,
  "ic-fish-simple": FishSimple,
  "ic-flag": Flag,
  "ic-flag-banner": FlagBanner,
  "ic-flag-banner-fold": FlagBannerFold,
  "ic-flag-checkered": FlagCheckered,
  "ic-flag-pennant": FlagPennant,
  "ic-flame": Flame,
  "ic-flashlight": Flashlight,
  "ic-flask": Flask,
  "ic-flip-horizontal": FlipHorizontal,
  "ic-flip-vertical": FlipVertical,
  "ic-floppy-disk": FloppyDisk,
  "ic-floppy-disk-back": FloppyDiskBack,
  "ic-flow-arrow": FlowArrow,
  "ic-flower": Flower,
  "ic-flower-lotus": FlowerLotus,
  "ic-flower-tulip": FlowerTulip,
  "ic-flying-saucer": FlyingSaucer,
  "ic-folder": Folder,
  "ic-folder-dashed": FolderDashed,
  "ic-folder-lock": FolderLock,
  "ic-folder-minus": FolderMinus,
  "ic-folder-open": FolderOpen,
  "ic-folder-plus": FolderPlus,
  "ic-folder-simple": FolderSimple,
  "ic-folder-simple-dashed": FolderSimpleDashed,
  "ic-folder-simple-lock": FolderSimpleLock,
  "ic-folder-simple-minus": FolderSimpleMinus,
  "ic-folder-simple-plus": FolderSimplePlus,
  "ic-folder-simple-star": FolderSimpleStar,
  "ic-folder-simple-user": FolderSimpleUser,
  "ic-folder-star": FolderStar,
  "ic-folder-user": FolderUser,
  "ic-folders": Folders,
  "ic-football": Football,
  "ic-football-helmet": FootballHelmet,
  "ic-footprints": Footprints,
  "ic-fork-knife": ForkKnife,
  "ic-four-k": FourK,
  "ic-frame-corners": FrameCorners,
  "ic-framer-logo": FramerLogo,
  "ic-function": Function,
  "ic-funnel": Funnel,
  "ic-funnel-simple": FunnelSimple,
  "ic-funnel-simple-x": FunnelSimpleX,
  "ic-funnel-x": FunnelX,
  "ic-game-controller": GameController,
  "ic-garage": Garage,
  "ic-gas-can": GasCan,
  "ic-gas-pump": GasPump,
  "ic-gauge": Gauge,
  "ic-gavel": Gavel,
  "ic-gear": Gear,
  "ic-gear-fine": GearFine,
  "ic-gear-six": GearSix,
  "ic-gender-female": GenderFemale,
  "ic-gender-intersex": GenderIntersex,
  "ic-gender-male": GenderMale,
  "ic-gender-neuter": GenderNeuter,
  "ic-gender-nonbinary": GenderNonbinary,
  "ic-gender-transgender": GenderTransgender,
  "ic-ghost": Ghost,
  "ic-gif": Gif,
  "ic-gift": Gift,
  "ic-git-branch": GitBranch,
  "ic-git-commit": GitCommit,
  "ic-git-diff": GitDiff,
  "ic-git-fork": GitFork,
  "ic-git-merge": GitMerge,
  "ic-git-pull-request": GitPullRequest,
  "ic-github-logo": GithubLogo,
  "ic-gitlab-logo": GitlabLogo,
  "ic-gitlab-logo-simple": GitlabLogoSimple,
  "ic-globe": Globe,
  "ic-globe-hemisphere-east": GlobeHemisphereEast,
  "ic-globe-hemisphere-west": GlobeHemisphereWest,
  "ic-globe-simple": GlobeSimple,
  "ic-globe-simple-x": GlobeSimpleX,
  "ic-globe-stand": GlobeStand,
  "ic-globe-x": GlobeX,
  "ic-goggles": Goggles,
  "ic-golf": Golf,
  "ic-goodreads-logo": GoodreadsLogo,
  "ic-google-cardboard-logo": GoogleCardboardLogo,
  "ic-google-chrome-logo": GoogleChromeLogo,
  "ic-google-drive-logo": GoogleDriveLogo,
  "ic-google-logo": GoogleLogo,
  "ic-google-photos-logo": GooglePhotosLogo,
  "ic-google-play-logo": GooglePlayLogo,
  "ic-google-podcasts-logo": GooglePodcastsLogo,
  "ic-gps": Gps,
  "ic-gps-fix": GpsFix,
  "ic-gps-slash": GpsSlash,
  "ic-gradient": Gradient,
  "ic-graduation-cap": GraduationCap,
  "ic-grains": Grains,
  "ic-grains-slash": GrainsSlash,
  "ic-graph": Graph,
  "ic-graphics-card": GraphicsCard,
  "ic-greater-than": GreaterThan,
  "ic-greater-than-or-equal": GreaterThanOrEqual,
  "ic-grid-four": GridFour,
  "ic-grid-nine": GridNine,
  "ic-guitar": Guitar,
  "ic-hair-dryer": HairDryer,
  "ic-hamburger": Hamburger,
  "ic-hammer": Hammer,
  "ic-hand": Hand,
  "ic-hand-arrow-down": HandArrowDown,
  "ic-hand-arrow-up": HandArrowUp,
  "ic-hand-coins": HandCoins,
  "ic-hand-deposit": HandDeposit,
  "ic-hand-eye": HandEye,
  "ic-hand-fist": HandFist,
  "ic-hand-grabbing": HandGrabbing,
  "ic-hand-heart": HandHeart,
  "ic-hand-palm": HandPalm,
  "ic-hand-peace": HandPeace,
  "ic-hand-pointing": HandPointing,
  "ic-hand-soap": HandSoap,
  "ic-hand-swipe-left": HandSwipeLeft,
  "ic-hand-swipe-right": HandSwipeRight,
  "ic-hand-tap": HandTap,
  "ic-hand-waving": HandWaving,
  "ic-hand-withdraw": HandWithdraw,
  "ic-handbag": Handbag,
  "ic-handbag-simple": HandbagSimple,
  "ic-hands-clapping": HandsClapping,
  "ic-hands-praying": HandsPraying,
  "ic-handshake": Handshake,
  "ic-hard-drive": HardDrive,
  "ic-hard-drives": HardDrives,
  "ic-hard-hat": HardHat,
  "ic-hash": Hash,
  "ic-hash-straight": HashStraight,
  "ic-head-circuit": HeadCircuit,
  "ic-headlights": Headlights,
  "ic-headphones": Headphones,
  "ic-headset": Headset,
  "ic-heart": Heart,
  "ic-heart-break": HeartBreak,
  "ic-heart-half": HeartHalf,
  "ic-heart-straight": HeartStraight,
  "ic-heart-straight-break": HeartStraightBreak,
  "ic-heartbeat": Heartbeat,
  "ic-hexagon": Hexagon,
  "ic-high-definition": HighDefinition,
  "ic-high-heel": HighHeel,
  "ic-highlighter": Highlighter,
  "ic-highlighter-circle": HighlighterCircle,
  "ic-hockey": Hockey,
  "ic-hoodie": Hoodie,
  "ic-horse": Horse,
  "ic-hospital": Hospital,
  "ic-hourglass": Hourglass,
  "ic-hourglass-high": HourglassHigh,
  "ic-hourglass-low": HourglassLow,
  "ic-hourglass-medium": HourglassMedium,
  "ic-hourglass-simple": HourglassSimple,
  "ic-hourglass-simple-high": HourglassSimpleHigh,
  "ic-hourglass-simple-low": HourglassSimpleLow,
  "ic-hourglass-simple-medium": HourglassSimpleMedium,
  "ic-house": House,
  "ic-house-line": HouseLine,
  "ic-house-simple": HouseSimple,
  "ic-hurricane": Hurricane,
  "ic-ice-cream": IceCream,
  "ic-identification-badge": IdentificationBadge,
  "ic-identification-card": IdentificationCard,
  "ic-image": Image,
  "ic-image-broken": ImageBroken,
  "ic-image-square": ImageSquare,
  "ic-images": Images,
  "ic-images-square": ImagesSquare,
  "ic-infinity": Infinity,
  "ic-info": Info,
  "ic-instagram-logo": InstagramLogo,
  "ic-intersect": Intersect,
  "ic-intersect-square": IntersectSquare,
  "ic-intersect-three": IntersectThree,
  "ic-intersection": Intersection,
  "ic-invoice": Invoice,
  "ic-island": Island,
  "ic-jar": Jar,
  "ic-jar-label": JarLabel,
  "ic-jeep": Jeep,
  "ic-joystick": Joystick,
  "ic-kanban": Kanban,
  "ic-key": Key,
  "ic-key-return": KeyReturn,
  "ic-keyboard": Keyboard,
  "ic-keyhole": Keyhole,
  "ic-knife": Knife,
  "ic-ladder": Ladder,
  "ic-ladder-simple": LadderSimple,
  "ic-lamp": Lamp,
  "ic-lamp-pendant": LampPendant,
  "ic-laptop": Laptop,
  "ic-lasso": Lasso,
  "ic-lastfm-logo": LastfmLogo,
  "ic-layout": Layout,
  "ic-leaf": Leaf,
  "ic-lectern": Lectern,
  "ic-lego": Lego,
  "ic-lego-smiley": LegoSmiley,
  "ic-less-than": LessThan,
  "ic-less-than-or-equal": LessThanOrEqual,
  "ic-letter-circle-h": LetterCircleH,
  "ic-letter-circle-p": LetterCircleP,
  "ic-letter-circle-v": LetterCircleV,
  "ic-lifebuoy": Lifebuoy,
  "ic-lightbulb": Lightbulb,
  "ic-lightbulb-filament": LightbulbFilament,
  "ic-lighthouse": Lighthouse,
  "ic-lightning": Lightning,
  "ic-lightning-a": LightningA,
  "ic-lightning-slash": LightningSlash,
  "ic-line-segment": LineSegment,
  "ic-line-segments": LineSegments,
  "ic-line-vertical": LineVertical,
  "ic-link": Link,
  "ic-link-break": LinkBreak,
  "ic-link-simple": LinkSimple,
  "ic-link-simple-break": LinkSimpleBreak,
  "ic-link-simple-horizontal": LinkSimpleHorizontal,
  "ic-link-simple-horizontal-break": LinkSimpleHorizontalBreak,
  "ic-linkedin-logo": LinkedinLogo,
  "ic-linktree-logo": LinktreeLogo,
  "ic-linux-logo": LinuxLogo,
  "ic-list": List,
  "ic-list-bullets": ListBullets,
  "ic-list-checks": ListChecks,
  "ic-list-dashes": ListDashes,
  "ic-list-heart": ListHeart,
  "ic-list-magnifying-glass": ListMagnifyingGlass,
  "ic-list-numbers": ListNumbers,
  "ic-list-plus": ListPlus,
  "ic-list-star": ListStar,
  "ic-lock": Lock,
  "ic-lock-key": LockKey,
  "ic-lock-key-open": LockKeyOpen,
  "ic-lock-laminated": LockLaminated,
  "ic-lock-laminated-open": LockLaminatedOpen,
  "ic-lock-open": LockOpen,
  "ic-lock-simple": LockSimple,
  "ic-lock-simple-open": LockSimpleOpen,
  "ic-lockers": Lockers,
  "ic-log": Log,
  "ic-magic-wand": MagicWand,
  "ic-magnet": Magnet,
  "ic-magnet-straight": MagnetStraight,
  "ic-magnifying-glass": MagnifyingGlass,
  "ic-magnifying-glass-minus": MagnifyingGlassMinus,
  "ic-magnifying-glass-plus": MagnifyingGlassPlus,
  "ic-mailbox": Mailbox,
  "ic-map-pin": MapPin,
  "ic-map-pin-area": MapPinArea,
  "ic-map-pin-line": MapPinLine,
  "ic-map-pin-plus": MapPinPlus,
  "ic-map-pin-simple": MapPinSimple,
  "ic-map-pin-simple-area": MapPinSimpleArea,
  "ic-map-pin-simple-line": MapPinSimpleLine,
  "ic-map-trifold": MapTrifold,
  "ic-markdown-logo": MarkdownLogo,
  "ic-marker-circle": MarkerCircle,
  "ic-martini": Martini,
  "ic-mask-happy": MaskHappy,
  "ic-mask-sad": MaskSad,
  "ic-mastodon-logo": MastodonLogo,
  "ic-math-operations": MathOperations,
  "ic-matrix-logo": MatrixLogo,
  "ic-medal": Medal,
  "ic-medal-military": MedalMilitary,
  "ic-medium-logo": MediumLogo,
  "ic-megaphone": Megaphone,
  "ic-megaphone-simple": MegaphoneSimple,
  "ic-member-of": MemberOf,
  "ic-memory": Memory,
  "ic-messenger-logo": MessengerLogo,
  "ic-meta-logo": MetaLogo,
  "ic-meteor": Meteor,
  "ic-metronome": Metronome,
  "ic-microphone": Microphone,
  "ic-microphone-slash": MicrophoneSlash,
  "ic-microphone-stage": MicrophoneStage,
  "ic-microscope": Microscope,
  "ic-microsoft-excel-logo": MicrosoftExcelLogo,
  "ic-microsoft-outlook-logo": MicrosoftOutlookLogo,
  "ic-microsoft-powerpoint-logo": MicrosoftPowerpointLogo,
  "ic-microsoft-teams-logo": MicrosoftTeamsLogo,
  "ic-microsoft-word-logo": MicrosoftWordLogo,
  "ic-minus": Minus,
  "ic-minus-circle": MinusCircle,
  "ic-minus-square": MinusSquare,
  "ic-money": Money,
  "ic-money-wavy": MoneyWavy,
  "ic-monitor": Monitor,
  "ic-monitor-arrow-up": MonitorArrowUp,
  "ic-monitor-play": MonitorPlay,
  "ic-moon": Moon,
  "ic-moon-stars": MoonStars,
  "ic-moped": Moped,
  "ic-moped-front": MopedFront,
  "ic-mosque": Mosque,
  "ic-motorcycle": Motorcycle,
  "ic-mountains": Mountains,
  "ic-mouse": Mouse,
  "ic-mouse-left-click": MouseLeftClick,
  "ic-mouse-middle-click": MouseMiddleClick,
  "ic-mouse-right-click": MouseRightClick,
  "ic-mouse-scroll": MouseScroll,
  "ic-mouse-simple": MouseSimple,
  "ic-music-note": MusicNote,
  "ic-music-note-simple": MusicNoteSimple,
  "ic-music-notes": MusicNotes,
  "ic-music-notes-minus": MusicNotesMinus,
  "ic-music-notes-plus": MusicNotesPlus,
  "ic-music-notes-simple": MusicNotesSimple,
  "ic-navigation-arrow": NavigationArrow,
  "ic-needle": Needle,
  "ic-network": Network,
  "ic-network-slash": NetworkSlash,
  "ic-network-x": NetworkX,
  "ic-newspaper": Newspaper,
  "ic-newspaper-clipping": NewspaperClipping,
  "ic-not-equals": NotEquals,
  "ic-not-member-of": NotMemberOf,
  "ic-not-subset-of": NotSubsetOf,
  "ic-not-superset-of": NotSupersetOf,
  "ic-notches": Notches,
  "ic-note": Note,
  "ic-note-blank": NoteBlank,
  "ic-note-pencil": NotePencil,
  "ic-notebook": Notebook,
  "ic-notepad": Notepad,
  "ic-notification": Notification,
  "ic-notion-logo": NotionLogo,
  "ic-nuclear-plant": NuclearPlant,
  "ic-number-circle-eight": NumberCircleEight,
  "ic-number-circle-five": NumberCircleFive,
  "ic-number-circle-four": NumberCircleFour,
  "ic-number-circle-nine": NumberCircleNine,
  "ic-number-circle-one": NumberCircleOne,
  "ic-number-circle-seven": NumberCircleSeven,
  "ic-number-circle-six": NumberCircleSix,
  "ic-number-circle-three": NumberCircleThree,
  "ic-number-circle-two": NumberCircleTwo,
  "ic-number-circle-zero": NumberCircleZero,
  "ic-number-eight": NumberEight,
  "ic-number-five": NumberFive,
  "ic-number-four": NumberFour,
  "ic-number-nine": NumberNine,
  "ic-number-one": NumberOne,
  "ic-number-seven": NumberSeven,
  "ic-number-six": NumberSix,
  "ic-number-square-eight": NumberSquareEight,
  "ic-number-square-five": NumberSquareFive,
  "ic-number-square-four": NumberSquareFour,
  "ic-number-square-nine": NumberSquareNine,
  "ic-number-square-one": NumberSquareOne,
  "ic-number-square-seven": NumberSquareSeven,
  "ic-number-square-six": NumberSquareSix,
  "ic-number-square-three": NumberSquareThree,
  "ic-number-square-two": NumberSquareTwo,
  "ic-number-square-zero": NumberSquareZero,
  "ic-number-three": NumberThree,
  "ic-number-two": NumberTwo,
  "ic-number-zero": NumberZero,
  "ic-numpad": Numpad,
  "ic-nut": Nut,
  "ic-ny-times-logo": NyTimesLogo,
  "ic-octagon": Octagon,
  "ic-office-chair": OfficeChair,
  "ic-onigiri": Onigiri,
  "ic-open-ai-logo": OpenAiLogo,
  "ic-option": Option,
  "ic-orange": Orange,
  "ic-orange-slice": OrangeSlice,
  "ic-oven": Oven,
  "ic-package": Package,
  "ic-paint-brush": PaintBrush,
  "ic-paint-brush-broad": PaintBrushBroad,
  "ic-paint-brush-household": PaintBrushHousehold,
  "ic-paint-bucket": PaintBucket,
  "ic-paint-roller": PaintRoller,
  "ic-palette": Palette,
  "ic-panorama": Panorama,
  "ic-pants": Pants,
  "ic-paper-plane": PaperPlane,
  "ic-paper-plane-right": PaperPlaneRight,
  "ic-paper-plane-tilt": PaperPlaneTilt,
  "ic-paperclip": Paperclip,
  "ic-paperclip-horizontal": PaperclipHorizontal,
  "ic-parachute": Parachute,
  "ic-paragraph": Paragraph,
  "ic-parallelogram": Parallelogram,
  "ic-park": Park,
  "ic-password": Password,
  "ic-path": Path,
  "ic-patreon-logo": PatreonLogo,
  "ic-pause": Pause,
  "ic-pause-circle": PauseCircle,
  "ic-paw-print": PawPrint,
  "ic-paypal-logo": PaypalLogo,
  "ic-peace": Peace,
  "ic-pen": Pen,
  "ic-pen-nib": PenNib,
  "ic-pen-nib-straight": PenNibStraight,
  "ic-pencil": Pencil,
  "ic-pencil-circle": PencilCircle,
  "ic-pencil-line": PencilLine,
  "ic-pencil-ruler": PencilRuler,
  "ic-pencil-simple": PencilSimple,
  "ic-pencil-simple-line": PencilSimpleLine,
  "ic-pencil-simple-slash": PencilSimpleSlash,
  "ic-pencil-slash": PencilSlash,
  "ic-pentagon": Pentagon,
  "ic-pentagram": Pentagram,
  "ic-pepper": Pepper,
  "ic-percent": Percent,
  "ic-person": Person,
  "ic-person-arms-spread": PersonArmsSpread,
  "ic-person-simple": PersonSimple,
  "ic-person-simple-bike": PersonSimpleBike,
  "ic-person-simple-circle": PersonSimpleCircle,
  "ic-person-simple-hike": PersonSimpleHike,
  "ic-person-simple-run": PersonSimpleRun,
  "ic-person-simple-ski": PersonSimpleSki,
  "ic-person-simple-snowboard": PersonSimpleSnowboard,
  "ic-person-simple-swim": PersonSimpleSwim,
  "ic-person-simple-tai-chi": PersonSimpleTaiChi,
  "ic-person-simple-throw": PersonSimpleThrow,
  "ic-person-simple-walk": PersonSimpleWalk,
  "ic-perspective": Perspective,
  "ic-phone": Phone,
  "ic-phone-call": PhoneCall,
  "ic-phone-disconnect": PhoneDisconnect,
  "ic-phone-incoming": PhoneIncoming,
  "ic-phone-list": PhoneList,
  "ic-phone-outgoing": PhoneOutgoing,
  "ic-phone-pause": PhonePause,
  "ic-phone-plus": PhonePlus,
  "ic-phone-slash": PhoneSlash,
  "ic-phone-transfer": PhoneTransfer,
  "ic-phone-x": PhoneX,
  "ic-phosphor-logo": PhosphorLogo,
  "ic-pi": Pi,
  "ic-piano-keys": PianoKeys,
  "ic-picnic-table": PicnicTable,
  "ic-picture-in-picture": PictureInPicture,
  "ic-piggy-bank": PiggyBank,
  "ic-pill": Pill,
  "ic-ping-pong": PingPong,
  "ic-pint-glass": PintGlass,
  "ic-pinterest-logo": PinterestLogo,
  "ic-pinwheel": Pinwheel,
  "ic-pipe": Pipe,
  "ic-pipe-wrench": PipeWrench,
  "ic-pix-logo": PixLogo,
  "ic-pizza": Pizza,
  "ic-placeholder": Placeholder,
  "ic-planet": Planet,
  "ic-plant": Plant,
  "ic-play": Play,
  "ic-play-circle": PlayCircle,
  "ic-play-pause": PlayPause,
  "ic-playlist": Playlist,
  "ic-plug": Plug,
  "ic-plug-charging": PlugCharging,
  "ic-plugs": Plugs,
  "ic-plugs-connected": PlugsConnected,
  "ic-plus": Plus,
  "ic-plus-circle": PlusCircle,
  "ic-plus-minus": PlusMinus,
  "ic-plus-square": PlusSquare,
  "ic-poker-chip": PokerChip,
  "ic-police-car": PoliceCar,
  "ic-polygon": Polygon,
  "ic-popcorn": Popcorn,
  "ic-popsicle": Popsicle,
  "ic-potted-plant": PottedPlant,
  "ic-power": Power,
  "ic-prescription": Prescription,
  "ic-presentation": Presentation,
  "ic-presentation-chart": PresentationChart,
  "ic-printer": Printer,
  "ic-prohibit": Prohibit,
  "ic-prohibit-inset": ProhibitInset,
  "ic-projector-screen": ProjectorScreen,
  "ic-projector-screen-chart": ProjectorScreenChart,
  "ic-pulse": Pulse,
  "ic-push-pin": PushPin,
  "ic-push-pin-simple": PushPinSimple,
  "ic-push-pin-simple-slash": PushPinSimpleSlash,
  "ic-push-pin-slash": PushPinSlash,
  "ic-puzzle-piece": PuzzlePiece,
  "ic-qr-code": QrCode,
  "ic-question": Question,
  "ic-question-mark": QuestionMark,
  "ic-queue": Queue,
  "ic-quotes": Quotes,
  "ic-rabbit": Rabbit,
  "ic-racquet": Racquet,
  "ic-radical": Radical,
  "ic-radio": Radio,
  "ic-radio-button": RadioButton,
  "ic-radioactive": Radioactive,
  "ic-rainbow": Rainbow,
  "ic-rainbow-cloud": RainbowCloud,
  "ic-ranking": Ranking,
  "ic-read-cv-logo": ReadCvLogo,
  "ic-receipt": Receipt,
  "ic-receipt-x": ReceiptX,
  "ic-record": Record,
  "ic-rectangle": Rectangle,
  "ic-rectangle-dashed": RectangleDashed,
  "ic-recycle": Recycle,
  "ic-reddit-logo": RedditLogo,
  "ic-repeat": Repeat,
  "ic-repeat-once": RepeatOnce,
  "ic-replit-logo": ReplitLogo,
  "ic-resize": Resize,
  "ic-rewind": Rewind,
  "ic-rewind-circle": RewindCircle,
  "ic-road-horizon": RoadHorizon,
  "ic-robot": Robot,
  "ic-rocket": Rocket,
  "ic-rocket-launch": RocketLaunch,
  "ic-rows": Rows,
  "ic-rows-plus-bottom": RowsPlusBottom,
  "ic-rows-plus-top": RowsPlusTop,
  "ic-rss": Rss,
  "ic-rss-simple": RssSimple,
  "ic-rug": Rug,
  "ic-ruler": Ruler,
  "ic-sailboat": Sailboat,
  "ic-scales": Scales,
  "ic-scan": Scan,
  "ic-scan-smiley": ScanSmiley,
  "ic-scissors": Scissors,
  "ic-scooter": Scooter,
  "ic-screencast": Screencast,
  "ic-screwdriver": Screwdriver,
  "ic-scribble": Scribble,
  "ic-scribble-loop": ScribbleLoop,
  "ic-scroll": Scroll,
  "ic-seal": Seal,
  "ic-seal-check": SealCheck,
  "ic-seal-percent": SealPercent,
  "ic-seal-question": SealQuestion,
  "ic-seal-warning": SealWarning,
  "ic-seat": Seat,
  "ic-seatbelt": Seatbelt,
  "ic-security-camera": SecurityCamera,
  "ic-selection": Selection,
  "ic-selection-all": SelectionAll,
  "ic-selection-background": SelectionBackground,
  "ic-selection-foreground": SelectionForeground,
  "ic-selection-inverse": SelectionInverse,
  "ic-selection-plus": SelectionPlus,
  "ic-selection-slash": SelectionSlash,
  "ic-shapes": Shapes,
  "ic-share": Share,
  "ic-share-fat": ShareFat,
  "ic-share-network": ShareNetwork,
  "ic-shield": Shield,
  "ic-shield-check": ShieldCheck,
  "ic-shield-checkered": ShieldCheckered,
  "ic-shield-chevron": ShieldChevron,
  "ic-shield-plus": ShieldPlus,
  "ic-shield-slash": ShieldSlash,
  "ic-shield-star": ShieldStar,
  "ic-shield-warning": ShieldWarning,
  "ic-shipping-container": ShippingContainer,
  "ic-shirt-folded": ShirtFolded,
  "ic-shooting-star": ShootingStar,
  "ic-shopping-bag": ShoppingBag,
  "ic-shopping-bag-open": ShoppingBagOpen,
  "ic-shopping-cart": ShoppingCart,
  "ic-shopping-cart-simple": ShoppingCartSimple,
  "ic-shovel": Shovel,
  "ic-shower": Shower,
  "ic-shrimp": Shrimp,
  "ic-shuffle": Shuffle,
  "ic-shuffle-angular": ShuffleAngular,
  "ic-shuffle-simple": ShuffleSimple,
  "ic-sidebar": Sidebar,
  "ic-sidebar-simple": SidebarSimple,
  "ic-sigma": Sigma,
  "ic-sign-in": SignIn,
  "ic-sign-out": SignOut,
  "ic-signature": Signature,
  "ic-signpost": Signpost,
  "ic-sim-card": SimCard,
  "ic-siren": Siren,
  "ic-sketch-logo": SketchLogo,
  "ic-skip-back": SkipBack,
  "ic-skip-back-circle": SkipBackCircle,
  "ic-skip-forward": SkipForward,
  "ic-skip-forward-circle": SkipForwardCircle,
  "ic-skull": Skull,
  "ic-skype-logo": SkypeLogo,
  "ic-slack-logo": SlackLogo,
  "ic-sliders": Sliders,
  "ic-sliders-horizontal": SlidersHorizontal,
  "ic-slideshow": Slideshow,
  "ic-smiley": Smiley,
  "ic-smiley-angry": SmileyAngry,
  "ic-smiley-blank": SmileyBlank,
  "ic-smiley-meh": SmileyMeh,
  "ic-smiley-melting": SmileyMelting,
  "ic-smiley-nervous": SmileyNervous,
  "ic-smiley-sad": SmileySad,
  "ic-smiley-sticker": SmileySticker,
  "ic-smiley-wink": SmileyWink,
  "ic-smiley-x-eyes": SmileyXEyes,
  "ic-snapchat-logo": SnapchatLogo,
  "ic-sneaker": Sneaker,
  "ic-sneaker-move": SneakerMove,
  "ic-snowflake": Snowflake,
  "ic-soccer-ball": SoccerBall,
  "ic-sock": Sock,
  "ic-solar-panel": SolarPanel,
  "ic-solar-roof": SolarRoof,
  "ic-sort-ascending": SortAscending,
  "ic-sort-descending": SortDescending,
  "ic-soundcloud-logo": SoundcloudLogo,
  "ic-spade": Spade,
  "ic-sparkle": Sparkle,
  "ic-speaker-hifi": SpeakerHifi,
  "ic-speaker-high": SpeakerHigh,
  "ic-speaker-low": SpeakerLow,
  "ic-speaker-none": SpeakerNone,
  "ic-speaker-simple-high": SpeakerSimpleHigh,
  "ic-speaker-simple-low": SpeakerSimpleLow,
  "ic-speaker-simple-none": SpeakerSimpleNone,
  "ic-speaker-simple-slash": SpeakerSimpleSlash,
  "ic-speaker-simple-x": SpeakerSimpleX,
  "ic-speaker-slash": SpeakerSlash,
  "ic-speaker-x": SpeakerX,
  "ic-speedometer": Speedometer,
  "ic-sphere": Sphere,
  "ic-spinner": Spinner,
  "ic-spinner-ball": SpinnerBall,
  "ic-spinner-gap": SpinnerGap,
  "ic-spiral": Spiral,
  "ic-split-horizontal": SplitHorizontal,
  "ic-split-vertical": SplitVertical,
  "ic-spotify-logo": SpotifyLogo,
  "ic-spray-bottle": SprayBottle,
  "ic-square": Square,
  "ic-square-half": SquareHalf,
  "ic-square-half-bottom": SquareHalfBottom,
  "ic-square-logo": SquareLogo,
  "ic-square-split-horizontal": SquareSplitHorizontal,
  "ic-square-split-vertical": SquareSplitVertical,
  "ic-squares-four": SquaresFour,
  "ic-stack": Stack,
  "ic-stack-minus": StackMinus,
  "ic-stack-overflow-logo": StackOverflowLogo,
  "ic-stack-plus": StackPlus,
  "ic-stack-simple": StackSimple,
  "ic-stairs": Stairs,
  "ic-stamp": Stamp,
  "ic-standard-definition": StandardDefinition,
  "ic-star": Star,
  "ic-star-and-crescent": StarAndCrescent,
  "ic-star-four": StarFour,
  "ic-star-half": StarHalf,
  "ic-star-of-david": StarOfDavid,
  "ic-steam-logo": SteamLogo,
  "ic-steering-wheel": SteeringWheel,
  "ic-steps": Steps,
  "ic-stethoscope": Stethoscope,
  "ic-sticker": Sticker,
  "ic-stool": Stool,
  "ic-stop": Stop,
  "ic-stop-circle": StopCircle,
  "ic-storefront": Storefront,
  "ic-strategy": Strategy,
  "ic-stripe-logo": StripeLogo,
  "ic-student": Student,
  "ic-subset-of": SubsetOf,
  "ic-subset-proper-of": SubsetProperOf,
  "ic-subtitles": Subtitles,
  "ic-subtitles-slash": SubtitlesSlash,
  "ic-subtract": Subtract,
  "ic-subtract-square": SubtractSquare,
  "ic-subway": Subway,
  "ic-suitcase": Suitcase,
  "ic-suitcase-rolling": SuitcaseRolling,
  "ic-suitcase-simple": SuitcaseSimple,
  "ic-sun": Sun,
  "ic-sun-dim": SunDim,
  "ic-sun-horizon": SunHorizon,
  "ic-sunglasses": Sunglasses,
  "ic-superset-of": SupersetOf,
  "ic-superset-proper-of": SupersetProperOf,
  "ic-swap": Swap,
  "ic-swatches": Swatches,
  "ic-swimming-pool": SwimmingPool,
  "ic-sword": Sword,
  "ic-synagogue": Synagogue,
  "ic-syringe": Syringe,
  "ic-t-shirt": TShirt,
  "ic-table": Table,
  "ic-tabs": Tabs,
  "ic-tag": Tag,
  "ic-tag-chevron": TagChevron,
  "ic-tag-simple": TagSimple,
  "ic-target": Target,
  "ic-taxi": Taxi,
  "ic-tea-bag": TeaBag,
  "ic-telegram-logo": TelegramLogo,
  "ic-television": Television,
  "ic-television-simple": TelevisionSimple,
  "ic-tennis-ball": TennisBall,
  "ic-tent": Tent,
  "ic-terminal": Terminal,
  "ic-terminal-window": TerminalWindow,
  "ic-test-tube": TestTube,
  "ic-text-a-underline": TextAUnderline,
  "ic-text-aa": TextAa,
  "ic-text-align-center": TextAlignCenter,
  "ic-text-align-justify": TextAlignJustify,
  "ic-text-align-left": TextAlignLeft,
  "ic-text-align-right": TextAlignRight,
  "ic-text-b": TextB,
  "ic-text-columns": TextColumns,
  "ic-text-h": TextH,
  "ic-text-h-five": TextHFive,
  "ic-text-h-four": TextHFour,
  "ic-text-h-one": TextHOne,
  "ic-text-h-six": TextHSix,
  "ic-text-h-three": TextHThree,
  "ic-text-h-two": TextHTwo,
  "ic-text-indent": TextIndent,
  "ic-text-italic": TextItalic,
  "ic-text-outdent": TextOutdent,
  "ic-text-strikethrough": TextStrikethrough,
  "ic-text-subscript": TextSubscript,
  "ic-text-superscript": TextSuperscript,
  "ic-text-t": TextT,
  "ic-text-t-slash": TextTSlash,
  "ic-text-underline": TextUnderline,
  "ic-textbox": Textbox,
  "ic-thermometer": Thermometer,
  "ic-thermometer-cold": ThermometerCold,
  "ic-thermometer-hot": ThermometerHot,
  "ic-thermometer-simple": ThermometerSimple,
  "ic-threads-logo": ThreadsLogo,
  "ic-three-d": ThreeD,
  "ic-thumbs-down": ThumbsDown,
  "ic-thumbs-up": ThumbsUp,
  "ic-ticket": Ticket,
  "ic-tidal-logo": TidalLogo,
  "ic-tiktok-logo": TiktokLogo,
  "ic-tilde": Tilde,
  "ic-timer": Timer,
  "ic-tip-jar": TipJar,
  "ic-tipi": Tipi,
  "ic-tire": Tire,
  "ic-toggle-left": ToggleLeft,
  "ic-toggle-right": ToggleRight,
  "ic-toilet": Toilet,
  "ic-toilet-paper": ToiletPaper,
  "ic-toolbox": Toolbox,
  "ic-tooth": Tooth,
  "ic-tornado": Tornado,
  "ic-tote": Tote,
  "ic-tote-simple": ToteSimple,
  "ic-towel": Towel,
  "ic-tractor": Tractor,
  "ic-trademark": Trademark,
  "ic-trademark-registered": TrademarkRegistered,
  "ic-traffic-cone": TrafficCone,
  "ic-traffic-sign": TrafficSign,
  "ic-traffic-signal": TrafficSignal,
  "ic-train": Train,
  "ic-train-regional": TrainRegional,
  "ic-train-simple": TrainSimple,
  "ic-tram": Tram,
  "ic-translate": Translate,
  "ic-trash": Trash,
  "ic-trash-simple": TrashSimple,
  "ic-tray": Tray,
  "ic-tray-arrow-down": TrayArrowDown,
  "ic-tray-arrow-up": TrayArrowUp,
  "ic-treasure-chest": TreasureChest,
  "ic-tree": Tree,
  "ic-tree-evergreen": TreeEvergreen,
  "ic-tree-palm": TreePalm,
  "ic-tree-structure": TreeStructure,
  "ic-tree-view": TreeView,
  "ic-trend-down": TrendDown,
  "ic-trend-up": TrendUp,
  "ic-triangle": Triangle,
  "ic-triangle-dashed": TriangleDashed,
  "ic-trolley": Trolley,
  "ic-trolley-suitcase": TrolleySuitcase,
  "ic-trophy": Trophy,
  "ic-truck": Truck,
  "ic-truck-trailer": TruckTrailer,
  "ic-tumblr-logo": TumblrLogo,
  "ic-twitch-logo": TwitchLogo,
  "ic-twitter-logo": TwitterLogo,
  "ic-umbrella": Umbrella,
  "ic-umbrella-simple": UmbrellaSimple,
  "ic-union": Union,
  "ic-unite": Unite,
  "ic-unite-square": UniteSquare,
  "ic-upload": Upload,
  "ic-upload-simple": UploadSimple,
  "ic-usb": Usb,
  "ic-user": User,
  "ic-user-check": UserCheck,
  "ic-user-circle": UserCircle,
  "ic-user-circle-check": UserCircleCheck,
  "ic-user-circle-dashed": UserCircleDashed,
  "ic-user-circle-gear": UserCircleGear,
  "ic-user-circle-minus": UserCircleMinus,
  "ic-user-circle-plus": UserCirclePlus,
  "ic-user-focus": UserFocus,
  "ic-user-gear": UserGear,
  "ic-user-list": UserList,
  "ic-user-minus": UserMinus,
  "ic-user-plus": UserPlus,
  "ic-user-rectangle": UserRectangle,
  "ic-user-sound": UserSound,
  "ic-user-square": UserSquare,
  "ic-user-switch": UserSwitch,
  "ic-users": Users,
  "ic-users-four": UsersFour,
  "ic-users-three": UsersThree,
  "ic-van": Van,
  "ic-vault": Vault,
  "ic-vector-three": VectorThree,
  "ic-vector-two": VectorTwo,
  "ic-vibrate": Vibrate,
  "ic-video": Video,
  "ic-video-camera": VideoCamera,
  "ic-video-camera-slash": VideoCameraSlash,
  "ic-video-conference": VideoConference,
  "ic-vignette": Vignette,
  "ic-vinyl-record": VinylRecord,
  "ic-virtual-reality": VirtualReality,
  "ic-virus": Virus,
  "ic-visor": Visor,
  "ic-voicemail": Voicemail,
  "ic-volleyball": Volleyball,
  "ic-wall": Wall,
  "ic-wallet": Wallet,
  "ic-warehouse": Warehouse,
  "ic-warning": Warning,
  "ic-warning-circle": WarningCircle,
  "ic-warning-diamond": WarningDiamond,
  "ic-warning-octagon": WarningOctagon,
  "ic-washing-machine": WashingMachine,
  "ic-watch": Watch,
  "ic-wave-sawtooth": WaveSawtooth,
  "ic-wave-sine": WaveSine,
  "ic-wave-square": WaveSquare,
  "ic-wave-triangle": WaveTriangle,
  "ic-waveform": Waveform,
  "ic-waveform-slash": WaveformSlash,
  "ic-waves": Waves,
  "ic-webcam": Webcam,
  "ic-webcam-slash": WebcamSlash,
  "ic-webhooks-logo": WebhooksLogo,
  "ic-wechat-logo": WechatLogo,
  "ic-whatsapp-logo": WhatsappLogo,
  "ic-wheelchair": Wheelchair,
  "ic-wheelchair-motion": WheelchairMotion,
  "ic-wifi-high": WifiHigh,
  "ic-wifi-low": WifiLow,
  "ic-wifi-medium": WifiMedium,
  "ic-wifi-none": WifiNone,
  "ic-wifi-slash": WifiSlash,
  "ic-wifi-x": WifiX,
  "ic-wind": Wind,
  "ic-windmill": Windmill,
  "ic-windows-logo": WindowsLogo,
  "ic-wine": Wine,
  "ic-wrench": Wrench,
  "ic-x": X,
  "ic-x-circle": XCircle,
  "ic-x-logo": XLogo,
  "ic-x-square": XSquare,
  "ic-yarn": Yarn,
  "ic-yin-yang": YinYang,
  "ic-youtube-logo": YoutubeLogo
} as Record<string, IconComponent>;

export const ICON_NAMES = Object.keys(ICON_REGISTRY);
